### ISSUE TITLE
Allow job dependencies in PR builds

### ISSUE THREAD

**Issue by edudar** [screwdriver-cd/screwdriver#1085]
**What happened**:
A pipeline that has job dependencies will only run jobs that require `~pr` for a pull request but won't run jobs that depend on these with `~pr`. Configuration example:
```
jobs:
  main:
    requires: [~pr, ~commit]
  client:
    requires: [main]
```
PR build runs `main` but completely ignores `client` job.

**What you expected to happen**:
We don't want to have different builds depending on whether it's pull request build or not. Some deviations here are OK like we won't likely publish binaries from PR build but when jobs run things like additional set of tests, let's sey integration, and we want to make sure they pass in PR build. Overall I'd expect that master and branch/PR builds would run identically unless it's explicitly configured.

**Comment by petey** [comment]
Yeah, I think this is kind of an arbitrary limit on on the workflow configuration right now. It would be important to have successive jobs retain the $SD_PULL_REQUEST value so that users could continue to gate script activity based on whether or not a job started as a result of a PR or not.

The UX surrounding how PRs are handled currently is a bit misleading when compared to the yaml config. See #909, #1010

**Comment by stolfi** [comment]
I agree on the UX. The fact that the flow diagrams show the chaining of the jobs is very misleading.

**Comment by jithin1987** [comment]
This will be solved with https://github.com/screwdriver-cd/screwdriver/issues/823
