### ISSUE TITLE
[UI] Group or filter commands by namespace

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1096]
There is no grouping or filtering feature for commands UI. We should add grouping feature with `/commands/namesapce` endpoint of UI or add input area to UI for filtering.

The same implementation with the template's (not implemented yet) may be better but I don't know how to implement the template's UI.

Reference: https://github.com/screwdriver-cd/screwdriver/issues/926
>  [UI] Group templates by namespace, group templates with no namespace

**Comment by tkyi** [comment]
Not sure where this discussion belongs, but there's also been mention of protecting namespaces so that only certain users or pipelines can publish to specific namespaces (https://github.com/screwdriver-cd/screwdriver/issues/926#issuecomment-390745861).

We had some ideas:
- use [Github organizations, Bitbucket teams, Gitlab groups](https://about.gitlab.com/2016/01/27/comparing-terms-gitlab-github-bitbucket/) to keep track of namespace permissions
- internally keep track of namespace <-> org(s) relationships in a namespace table
Example table entry:
```
namespace: nodejs
admins: [github:nodejs, github:d2lam, bitbucket:nodejsTeam, gitlab:nodejsGroup]
```
- people can interact with it using the UI/API
- we will share namespace access between commands and templates
- everything should be backwards compatible

**Comment by tkyi** [comment]
For the UI, we were looking at [how Wercker does their steps UI](https://app.wercker.com/steps), since it's pretty similar to commands/templates, and we're going to talk to our design team to get some mocks/feedback.

**Comment by tk3fftk** [comment]
Command's namespace view is looks broken. The same commands are shown several times (number of versions). 
https://cd.screwdriver.cd/commands/namespaces/FenrirUnbound
![image](https://user-images.githubusercontent.com/3445553/42856802-ca406530-8a81-11e8-9070-c2a5b7fc7184.png)
