### ISSUE TITLE
Allow user defined teardown steps

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1126]
## Context

Enable user to define steps which will be run as part of teardown process. This will allow user to define cleanup commands which should run always

## Objective

1. Enable user to define a step which will run in teardown stage.
1. User defined teardown step should run befoer system defined teardown steps

**Comment by d2lam** [comment]
Some clarification:
For user teardown steps, do they need to be at the end?
```
- step1
- step2
- step3
- user-teardown-1
- user-teardown-2
- sd-teardown
```
If that's the case, then having multiple user-teardown is kinda useless, because `user-teardown-1` and `user-teardown-2` can basically be combined into one single user-teardown step. With this case, we can default to run `user-teardown` in a separate shell no matter if previous steps pass or fail. It behaves the same way as `sd-teardown`. 

If they can be in the middle like this:
```
- step1
- user-teardown-1
- step2
- user-teardown-2
- step3
- sd-teardown
```
Then there might be a couple cases:
- step2 passes, `user-teardown-2` will run in the same shell
- step2 fails, `user-teardown-2` will be run in a separate shell
These two cases will give different behaviors. Are we ok with that?

**Comment by d2lam** [comment]
1. Okay. I can do teardown steps at the end. Implementation wise it doesn't matter to support multiple.
2. I can look into seeding the env to the next shell. For the first pass, I will do it without env passing. 

Another question:
- Do we want config validator to fail if users don't put the `teardown` steps at the end?

**Comment by jithin1987** [comment]
>  Do we want config validator to fail if users don't put the teardown steps at the end? Or we can let it proceed and still run the teardown at the end?

Since we are doing teardown steps at end, validatior should fail if user uses these steps in non-end positions. But I am open to your original proposal of allowing the in middle if implementation wise bothe approaches are similar and we can find a way to seed the shell.

**Comment by d2lam** [comment]
@jithin1987 Implementation will be different between first and second approach. The 2nd one is more complicated because for first one we will ALWAYS run teardown in separate shells. For 2nd one, sometimes it is in same shell, sometimes it is in a different shell (depending on whether previous step fails or succeeds)

**Comment by d2lam** [comment]
This feature is done.
Example repo: https://github.com/screwdriver-cd-test/user-teardown-example
Example pipeline: https://cd.screwdriver.cd/pipelines/1190/events

For seeding ENV, we will open a separate issue if there is a need & request from users.
