### ISSUE TITLE
Timeout for jenkins executor

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1159]
# Context
There is timeout feature which has already implemented.
https://docs.screwdriver.cd/user-guide/configuration/annotations
But jenkins-executor does not handle `timeout` annotation currently.

# Objective
* Support timeout feature for jenkins-executor

**Comment by jithin1987** [comment]
@Filbird Perhaps the change for internal jenkins executor can be back-ported here.

**Comment by Filbird** [comment]
Unfortunately it will not be as straightforward since our change made use of a few internal Jenkins packages.

@catto If there's anything you would like me to assist with please feel free to reach out 😄 .

**Comment by jithin1987** [comment]
@Filbird is there way to not depend on internal Jenkins packages and relay on opensource ones ?

**Comment by Filbird** [comment]
I'm sure there is, will have to dig around a bit to figure out where exactly. I believe the internal packages already abstract over the open source variants, hence why the fix was so simple on our end.

If we want to solely depend on open source packages, then I think we'll have to rewrite a huge chunk of our internal executor.

**Comment by jithin1987** [comment]
> If we want to solely depend on open source packages, then I think we'll have to rewrite a huge chunk of our internal executor.

never mind then
