### ISSUE TITLE
Duration wrong for events 

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1173]
## Context

Duration displayed in Pipeline events page is wrong for cases when number of builds run as part of the event does not match overall number of builds possible in pipeline. Ex: Pipeline which uses `sourcePaths`

## Objective

1. Store event end time when we can detect there are no more builds to be executed as part of an event 
2. UI to use event end time to display duration for an event

**Comment by minz1027** [comment]
@jithin1987 Instead of doing extra logic to figure out if there are extra builds to run. Can we just keep updating the endTime whenever a build belongs to the event finishes?

**Comment by minz1027** [comment]
Discussed with Jithin about this, we actually need the `endTime` to determine if the event finishes to do some reload. So my proposal for a dynamic endTime won't work in this case.

@jithin1987 suggests to handle this in the UI. Instead of checking number of builds and compare with the workflowGraph. UI can get all builds for an event, if there is build running, mark it as `isRunning`. If all build finishes, delay for certain time (e.g. 5 secs) and then get all builds for the event again to see if there are new builds. If no, mark event as `isComplete`.

**Comment by minz1027** [comment]
Fixed.

<img width="993" alt="screen shot 2018-07-20 at 1 47 44 pm" src="https://user-images.githubusercontent.com/20427140/43024549-97fa1cee-8c23-11e8-9127-11bfdb18cc25.png">
