### ISSUE TITLE
Take a lot of time to see GitHub status

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1220]
**What happened**:

When I open PR, it took almost 10 sec to create GitHub status. 
This looks like caused by recursive API requests.

![t1wjd5b59731d24010a634b374fb4](https://user-images.githubusercontent.com/4645011/43248325-7a4326b8-90f2-11e8-938d-0e5c815487de.png)

![fw0cs5b59729c97b5506345601bd7](https://user-images.githubusercontent.com/4645011/43248322-772b58ba-90f2-11e8-9d25-3e11e0b893bb.png)

![dvwl05b59727b97b5506345601bd4](https://user-images.githubusercontent.com/4645011/43248319-74082230-90f2-11e8-9fc5-d11e6ddb2872.png)

**What you expected to happen**:

Create build with minimum API requests and able to see GitHub status more quickly.

**How to reproduce it**:
Open new PR requests.

**Comment by catto** [comment]
I confirmed that the number of accesses was reduced by using the latest API.
![image](https://user-images.githubusercontent.com/1608595/44965572-43e44a00-af71-11e8-943a-8bcbbc6cfb9e.png)
But it still queries GitHub API many times during processing PR open event. I think [this](https://github.com/screwdriver-cd/models/blob/a2c4cf9d9ad77d873639724a7e68d32598deeb66/lib/pipeline.js#L153) code is the main cause of this issue.
It waits for GitHub async ops, but shouldn't exist here because of a dependent to GitHub specific thing. Also `getConfiguration` is called three times during PR event, so it wastes 5.4 seconds.

Screwdriver should wait the async ops one time only before the process of webhook and it should in scm-github module.

**Comment by catto** [comment]
I have finally confirmed that it takes only a few seconds to update a commit status with the latest API. (before: 13~30 secs depends on pipeline)
![image](https://user-images.githubusercontent.com/1608595/44979466-28486600-afa8-11e8-92eb-1ae8691d6679.png)

There are some duplicated GitHub API calls. We should reduce them in another issue.
