### ISSUE TITLE
[feature request] [UI] redirect to new template detail pages from old URL

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1231]
**What happened**:
Our internal documents have old URL ( like `/templates/<namespace>%2F<name>`). URL of template detail pages have changed so old URL is not found. Updating all links is hard 😥 

**What you expected to happen**:
UI redirects to new URL (`/templates/namespaces/<namespace>/names/<name>`) when we access old URL.

**Comment by jithin1987** [comment]
@tk3fftk is it too much of a work to update the links ? I would rather not have this done in UI, because it's not a simple redirection. We need to have a route which parses the `<namespace>%2F<name>` (it's a single path param) and then do a redirection.

Doable but would prefer not to have this logic in UI codebase.

**Comment by tk3fftk** [comment]
In hour environment, link texts are converted so we cannot replace link texts at one time.
Our update steps are below:
1. go to edit page
2. click link text to open a modal for link edit
3. update link (this is tired because new template link is verbose. related: https://github.com/screwdriver-cd/screwdriver/issues/1230 )
4. continue 1-3 steps for each template links 
5. continue 1-4 step for each pages (There are about 20 pages)

**Comment by tkyi** [comment]
We recently changed the url back to `/templates/<namespace>/<name>`. But there's also a `/templates/<namespace>`, making it tricky for me to figure out how to redirect from the old URL (`/templates/<namespace>%2F<name>`) to the new one.
