### ISSUE TITLE
Capture and store build stats

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1270]
## Context

Build detail API lacks information on execution context. For example

1. Time when build was send to executor
1. Host where build was executed
1. Time when the k8s pod was setup
1. Time it took to fetch build container.
1. Time it took to create VM

## Objective

Store build status so that `GET` build API has more information on the build which can be used in various context. 

Eg: 
1. Build hostname can be used to debug build slave issues.
1. Time information can be used to provide user information on [specific stages of build](https://github.com/screwdriver-cd/screwdriver/issues/1198).

**Comment by d2lam** [comment]
I took a look at this issue and think we should group them to this:
- Build is enqueued
- Build pulling image, on host ___
- Build starts executing steps

The above will capture your requirements like this: 
- Time when build was send to executor (executor queue to be precise?)
- Time when the k8s pod was setup/Time it took to create VM/Host where build was executed
- Time it took to fetch build container

I think we should group the k8s pod + VM since that's very low level. User will not (and should not need to) understand the difference between creating a k8s pod and creating a VM. To them, it's 3 stages: waiting in queue, start pulling image, and build executing.

**Comment by jithin1987** [comment]
@d2lam sounds good. Objective is to be open display to user each part of our system which contributes to the build time from the moment a build is created.

**Comment by d2lam** [comment]
### Update 12/24/2018
All builds now have the field `stats` that includes:
- `queueEnterTime`: time the build gets enqueue
- `hostname`: where the build runs on (for k8s and k8s-vm executor)

Still need to work on `imagePullStartTime`, but I will be on vacation for some time. So please feel free to continue working on it, or I can finish up when I'm back :)

**Comment by minz1027** [comment]
### updates on 01/04

Basically, after the pod got scheduled to a node, it will start volume mounting and image pulling. If we're not going to separate volume mount, init container and image pulling into different events, we can just set the `imagePullStartTime ` when we set the `hostname`.
