### ISSUE TITLE
Search query should be case insensitive

### ISSUE THREAD

**Issue by taisukeh** [screwdriver-cd/screwdriver#1272]
**What happened**:

Currently, the pipeline search query is case sensitive.

**What you expected to happen**:

The pipeline search query should be case insensitive.

**How to reproduce it**:

Search [Filbird/sd-cmd-test](https://cd.screwdriver.cd/pipelines/1244/events) pipeline by `filbird`.

**Comment by tkyi** [comment]
We're switching to moving search functionality to the datastore. Since we're using [sequelize](https://www.npmjs.com/package/sequelize), we're stuck with the case-sensitive search, since ILIKE is only available for postgres (http://docs.sequelizejs.com/manual/tutorial/querying.html#operators).

**Comment by d2lam** [comment]
### Update 3/21/2019
Added a PR to address this issue. It will check if the dialect is `postgres`. If it is, it will use case insensitive search. Otherwise, fall back to the current behavior.

**Comment by minz1027** [comment]
@taisukeh This behavior can be tuned by `collation` of the DB or column and it should work for the sql dbs we support. But since we don't set it in the first place, to do it now we need to `alter table` which is kinda expensive to do...

https://stackoverflow.com/questions/2876789/how-can-i-search-case-insensitive-in-a-column-using-like-wildcard 

https://github.com/sequelize/sequelize/issues/7110

**Comment by d2lam** [comment]
This is now working for `cd.screwdriver.cd`, since our DB is postgres. 
<img width="727" alt="Screen Shot 2019-03-25 at 4 28 15 PM" src="https://user-images.githubusercontent.com/3401924/54960695-064e0b00-4f1b-11e9-8149-04837361c27a.png">

**Comment by taisukeh** [comment]
Thanks so much!
