### ISSUE TITLE
[Build cache] Implement cache service

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1281]
## Context
In order to provide build cache feature, there should be new cache service which stores build caches with options such as a scope, an expiration option and so on.

## Objective
- [x] Implement cache service as a separated component
  - [x] Detailed design (in addition to [proposal](https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md#server))
    - Auth method: SD_TOKEN?
    - Compression: use or not. which method should we take
  - [x] Determine which backends should we support
- [x] Pipeline to deploy the service
- [x] Pass an endpoint of cache service to each build environment so that `cache` cli can access to it

## References
Original issue: #1257

**Comment by d2lam** [comment]
We will implement this for events as first pass since we think that is the most useful.

**Comment by d2lam** [comment]
### Update 9/24
Decided to combine the cache service with the store service, since they are both interacting with S3 in a similar way. Therefore, I marked the last 2 items in the TODO list as `DONE` since they are no longer necessary. 
- For auth method, we will use JWT. This is a build upload a file to `bucket/caches/events/EVENT_ID/CACHENAME`: https://cd.screwdriver.cd/pipelines/173/builds/67734
This is a build that fails to upload due to auth: https://cd.screwdriver.cd/pipelines/173/builds/67735
- For compression, we will most likely do it but not in the first pass. We will do it in second pass. 

@catto  I have a few questions:
- What is "Determine which backends should we support"
- This is storage location, let me know if it's ok (right now we just started with events):
_Events: bucket/caches/events/eventId
Pipelines: bucket/caches/pipelines/pipelineId
Jobs: bucket/caches/job/jobId_

**Comment by catto** [comment]
@d2lam What I meant was that we should consider supporting storage backend other than S3 such as a local disk for in-a-box. Now store handles cache objects via catbox and we don't need to do it.
The storage location looks good to me 🙆

**Comment by d2lam** [comment]
### Update 9/26/2018
We decided on the following:
- **GET**: after get, update the `Last Modified` field in the cache. In S3, we set the lifecycle policy (for example 7 days). Therefore, `Last Modified` field needs to be updated whenever there is a new `GET`. If not using S3, this step is skipped.
- **SET**: we want to only upload the changed files, so we looked into [S3 sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) and [rclone](https://rclone.org/s3/#amazon-s3). This needs to be done inside the build because it involves a local directory. However, we cannot expose S3 secrets (access key id, secret keys, etc). Therefore, we cannot use them in a secured way. We decided to upload as long as there is a change to the zip file by comparing the checksum.

**Comment by d2lam** [comment]
@catto We looked into using Redis. I believe the decision was it is not efficient for large file. Do you have any other suggestion? For us, it seems the simplest way is to use S3. But we might need to refactor in the future to make it more pluggable in case other people are not using S3.
