### ISSUE TITLE
Stop parallel builds require a hard task

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1285]
**What happened**:
Can not stop parallel builds by step.
When I try to stop parallel builds, I need to stop one by one. It very tough things for me.

**What you expected to happen**:
I want to stop all parallel builds by one step.

**How to reproduce it**:
Running parallel builds and try to stop every these builds.

**Comment by yoshwata** [comment]
Some new UIs are needed to deal with this issue.

### For normal events
My proposal is like below. A new `Stop` button is on UI, next of `DURATION`.
<img width="1287" alt="collage2" src="https://user-images.githubusercontent.com/32473622/53146950-60407580-35e9-11e9-8ade-d62a9c972bc7.png">

After the `Stop` is pushed, all `QUEUED` or `RUNNING` jobs are stopped. The stop button is not shown at this situation because there are no jobs to stop.
![screen shot 2019-02-21 at 14 01 02](https://user-images.githubusercontent.com/32473622/53147228-3f2c5480-35ea-11e9-9602-c32d63d0e665.jpg)

### For pr events
For PR events, I propose UI like below. PR jobs are surrounded by frame. It gathers PR events by each PR. A stop button is put on frames of non stopped events.
![collage5](https://user-images.githubusercontent.com/32473622/53147239-4b181680-35ea-11e9-8638-eb1939c1bb50.jpg)

Is it reasonable? Are there better idea?

**Comment by wahapo** [comment]
I have another idea. It is a proposal that put the link of `Stop all builds in this event` in the tooltip. In addition, we are also good to fill the tooltip in the swirl on the right side.
<img width="1215" src="https://user-images.githubusercontent.com/24538326/53157887-caffaa00-3605-11e9-9334-51b8c93aad51.png">

**Comment by yoshwata** [comment]
Thanks @wahapo! I tried to write image of PR pattern in your idea. Is it make your sence?
<img width="1306" alt="collage7" src="https://user-images.githubusercontent.com/32473622/53219820-e968b280-36a4-11e9-944f-b6163e308d7a.png">

**Comment by jithin1987** [comment]
The Pull Request section will have to have a re-design when we PR chain feature is functional. It will have to behave similar to how events, does. Infact nothing prevents us from implementing the same today, ie Pull Requests section should show pull request events instead of jobs. So there won't be multiple cards for each parallel jobs but one card for one event which shows all parallel jobs. 

I like this idea https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-465928533
, but I would like to see an explicit button next to the big graph, if any jobs are Running.

**Comment by yoshwata** [comment]
Thanks @jithin. I drop idea of PR card UI because of prchain feature now.
It is better to think again after prchain become functional.

I tried to write jithin's idea.
![collage10](https://user-images.githubusercontent.com/32473622/53228673-3bb9cb80-36c5-11e9-961b-cbc7c8a4ad69.jpg)

It is fixed version that to float at upper right side for user of huge pipelines.
![collage9](https://user-images.githubusercontent.com/32473622/53228687-45dbca00-36c5-11e9-98ce-73e56a3d5bbc.jpg)

Is it better?

**Comment by yoshwata** [comment]
My favorite is upper right button now.

**Comment by tkyi** [comment]
- I prefer upper right button (next to duration) (https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-465874779)
- Random thought: Would it be better if people could select a bunch of jobs or all jobs in an event to disable at once?
- Question: Will `BLOCKED`, `FROZEN` etc builds also be stopped?

**Comment by yoshwata** [comment]
Thanks @tkyi. 

> Would it be better if people could select a bunch of jobs or all jobs in an event to disable at once?

It seems to be nice. Selected or checking interface will be needed to implement it in the future.
If I or our users feel the importance of the idea, I will make the issue. That might not be the idea of just for stopping. 

> Question: Will `BLOCKED`, `FROZEN` etc builds also be stopped?

Yes! All jobs that is running or that are going to run should be stopped.

**Comment by yoshwata** [comment]
These are not on context of this issue but very nice idea. (I'll make other issues)
- Stopping single job from big pipeline graph (https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-465928533)
- Job selecting interface (https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-466512261)
- PR job (https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-466269598)

What should I refere to
- API to stop jobs
- state of jobs to stop

**Comment by yoshwata** [comment]
## Update 

### UI image
Upper right side floating button makes sence for people who mange big or small pipelines.
![collage9](https://user-images.githubusercontent.com/32473622/53313713-0a781000-38fe-11e9-9582-460946416e61.jpg)

### API design

Add new api like
```
/v4/events/{id}/stop
```

`stopall` api is a candidate to stop all events in a pipeline.

### State of builds to be stopped
```
CREATED
QUEUED
RUNNING
BLOCKED
COLLAPSED
FROZEN
```

**Comment by jithin1987** [comment]
Also can I suggest one more function. Stopping a build from pipeline event graph

<img width="292" alt="screen shot 2019-02-25 at 6 20 14 pm" src="https://user-images.githubusercontent.com/193126/53382720-095cd800-392a-11e9-924e-33f44d22c9bc.png">

**Comment by yoshwata** [comment]
>Also can I suggest one more function. Stopping a build from pipeline event graph

Thanks, your suggestion seems to correspond with this issue. 
https://github.com/screwdriver-cd/screwdriver/issues/1516

**Comment by yoshwata** [comment]
Thank you!!
