### ISSUE TITLE
Start event with meta data - parameterized builds

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1339]
## Objective

API has the ability to start an event with custom meta data. This can be exposed in UI to support parametrized builds. 

## Objective

1. Clicking `Start` button should have a UI element for user to provide meta data. (key value pairs)
1. Clicking `Start Pipeline from here` on pipeline event graph should have a UI element to provide meta data (key value pairs) 
1. Build to expose the data under key `event-inputs` (perhaps another better name)

## References

https://api.screwdriver.cd/v4/documentation#!/v4/postV4Events

**Comment by tk3fftk** [comment]
This feature would be very useful in some case.
But we concern that the feature may decrease build reproducibility and make hard to track trouble of builds.
How about adding a cluster wide feature flag to toggle this feature enabled/disabled by admins?

**Comment by jithin1987** [comment]
>  But we concern that the feature may decrease build reproducibility and make hard to track trouble of builds.

Since all the information is persisted in event metadata, I believe build reproducibility is guaranteed. If user want to re-run the build with same parameters, then user can follow same steps user does today - select the event and re-run the build. 

What we need to do from a UX perspective it to highlight parameters in a better way than just pass it to event API. For example, `sd-init-step` can log all parameters. Event graph can display them to better highlight the fact that this event was started with parameters. 

I am open to hiding this behind a feature flag. cc @adong

**Comment by jithin1987** [comment]
Current proposal. `parameters` will be a top level config for pipeline.

```
parameters:
   auth_strategy: simple
   user:
     value: jitthin
     description: User running build
jobs:
  build:
...
```

Only pipelines which have `parameters` config in their `screwdriver.yaml` will see option to enter parameters when triggering Start button and will see only the parameters which are in the `screwdriver.yaml`.

`parameters` will be made available in the build via meta data using key  `parameters`. Events API already supports passing in meta data, so meta data will be a good vehicle to pass in the inputs. 

Now if we have pipelines triggering each other, we need a way to triggering pipeline to pass information if the triggered one is parameterized.
