### ISSUE TITLE
Trusted templates & commands

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1427]
## Context

Trust implementation for Templates & Commands is a continuation of work from https://github.com/screwdriver-cd/screwdriver/issues/1271

## Objective
1. Design backend for marking a template/command as trusted.
1. UI to highlight trusted templates/commands . Refer [mocks](https://github.com/screwdriver-cd/screwdriver/issues/1271#issuecomment-426421541)

## References

1. Feature discussion - https://github.com/screwdriver-cd/screwdriver/issues/1271#issuecomment-430828998 
2. Namespace auth - https://github.com/screwdriver-cd/screwdriver/issues/1121

**Comment by frankthrock** [comment]
It might be interesting to include a count of the number of times each template was used in the n days to give a sense of stability...

**Comment by d2lam** [comment]
So there are 2 ways to approach this:

### **Screwdriver admins decide what is trusted**
- Pros: simple implementation. We have a separate table with template namespace, name, and a flag to mark it's trusted or not. 
- Cons: maintenance will get out of hand. Cluster admins will be the bottleneck. When template owners request to mark their template as trusted, how do you decide? Do you need to go through a set of steps to verify it? Or is it merely based on the trusting relationship with the template owner? Also, this action is done manually. 

### **Screwdriver users decide what is trusted** 
We can use a combination of how github & npm does it. Users can **star** a template. Templates with more stars can be interpreted as more trusted. Additionally, we can have fields such as **last published** and **download counts**. These fields need to be auto updated when a template is created, and when a template is used. 
- Pros: There will be no maintenance required by the cluster admins since the users decide what is trusted or not. Also, not every template needs to be "official" to be useful. This approach can let the users decide what's useful rather than us deciding what's good for them.  
- Cons: Implementation will be trickier. 

Having something "officially approved by the Screwdriver team" (approach #1) sounds assuring, but most of the time the Screwdriver team *doesn't* have the knowledge of what all these templates do. We cannot decide what is good/bad. I think letting the users decide would be more appropriate.

**Comment by tkyi** [comment]
I agree and I like the `Screwdriver users decide what is trusted` option better.

The first option seems to have a lot of overhead cost and is unsustainable. The second option has a higher initial cost but I think it will be better in the long run.

**Comment by jithin1987** [comment]
We can't just leave it to users to decide popularity. What trusted means in context of a SD cluster is that the admins of the SD cluster has some sort of vetting done. We won't have thousands of templates to be marked as trusted, only few 10's of templates which are maintained by a trusted developer/team. 

Last published/usage count/user stars are all good metrics to surface up to users, but they can't be analogous to a trust relationship. They are secondary attributes which I definitely want to capture. 
In future if we do open up a market place for templates and commands (for open source) vetting by SD admins becomes important, in addition to usage popularity. 

Lets go with options 1. Option 2 are secondary features.

**Comment by d2lam** [comment]
>In future if we do open up a market place for templates and commands (for open source), vetting by SD admins becomes important, in addition to usage popularity.

Why would "vetting by SD admins" become important? If we take a look at npm packages for example, if you search for `json parser`, there are hundreds of packages to do that. But the npm team doesn't say which package is trusted by them because doing so is not scalable. 

> We won't have thousands of templates to be marked as trusted, only few 10's of templates which are maintained by a trusted developer/team.

If this is the case, why do we need to implement a separate table and endpoints to maintain at all? Can't we simply make a hardcoded list and show it on templates page?

**Comment by DekusDenial** [comment]
As per our discussion, for enterprise community, this will require legitimate support from domain experts who are responsible to establish templates (and/or commands) promoting best practices and defining standardized workflow, and are highly welcomed by the communities involved.

In simple terms, this is more about (present & future) maintainability and less about reputation (ranked by high usage). We will define the process and criterion of how one namespace, thus its templates & commands, becomes `Trusted`

**Comment by jithin1987** [comment]
I think the granularity level should be template itself, rather than the entire namespce. That will be a blanket approval to get any templates/commands as trusted.

**Comment by frankthrock** [comment]
I agree with @jithin1987 here on both points.  1) Trusted means that the template has been vetted by the SD admins.  In this context, this means that if you use this template, you can be certain that your pipeline meets the company guidelines for that particular platform.  Consistent use of the trusted templates allows us to collect metrics for a given platform as well.  2) The 'trusted' flag should apply to a particular template or command, not an entire namespace.

**Comment by DekusDenial** [comment]
Will begin the inquiry standardization process
