### ISSUE TITLE
Authentication failed getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by arunpnetskope** [screwdriver-cd/screwdriver#1431]
I am facing 401 error while login redirected to api, but at the same time other user (from my team) is able to authenticate. Next day I am able to login but he can't.

Is there any limit set to users which I can modify to resolve this ? I get below error - 

`{"statusCode":401,"error":"Unauthorized","message":"Authentication failed due to: Client request error: getaddrinfo ENOTFOUND github.com github.com:443"}`

api version: 0.5.486

**Comment by gthosaniNetskope** [comment]
@jithin1987, @vengopal can u please look into this issue at your earliest convenience ?

Some background on the issue, the IP of the SD service was changed and accordingly we changed the GIT webhooks. Since then there were multiple attempts made by all of us. Would like to understand if there is a rate limiting feature in SD and/or github which could be playing a role in SD login ?

**Comment by arunpnetskope** [comment]
@jithin1987 Not sure if this is a network related issue... coz another user is able to login at his end. 

Api, UI and store are running in single k8 node (1 master and 1 node).

**Comment by jithin1987** [comment]
Closing this since this issue is an cluster setup one.
