### ISSUE TITLE
Expose additional Details of Pull Request in build

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1437]
1. Changed files
1. PR Author
1. PR Subject
1. PR Description

Exposing these information will help users whose builds  do processing based on PR content

**Comment by jithin1987** [comment]
Getting the entire changed files also depends on fixing this https://github.com/screwdriver-cd/screwdriver/issues/1510

**Comment by tkyi** [comment]
2. PR Author might be related to another issue: https://github.com/screwdriver-cd/screwdriver/issues/1407#issuecomment-480106118

**Comment by minz1027** [comment]
Shall we make this generic for both PR and commits? 

e.g.
COMMIT_CHANGED_FILES
COMMIT_AUTHOR
COMMIT_ SUBJECT / COMMIT_MESSAGE

feel description is a little bit too much?

**Comment by minz1027** [comment]
### 04/19
Since we have `COMMIT_AUTHOR`, `COMMIT_MESSAGE` and `COMMIT_CHANGED_FILES `already from the eventFactory, will add these first. If we really want `COMMIT_DESCRIPTION`, we need to add it to the decorated commit object later.

**Comment by tkyi** [comment]
I like having them more generic for PR and commit
not sure about names

**Comment by minz1027** [comment]
### updates 04/23
Discussed with Jithin, we will also add an additional var commit_committer since author and committer may not be the same guy. And we can decide later how to display this in the UI if they are not the same. https://github.com/screwdriver-cd/screwdriver/issues/1407#issuecomment-480106118 @tkyi
