### ISSUE TITLE
Analyzed code coverage data aren't cleaned up

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1579]
**What happened**:
Current implementation of coverage-sonar bookend sends `sonar.projectVersion` with value `$SD_BUILD_SHA`. It creates "event" in sonarqube and they aren't cleaned up by housekeeping feature. This behavior leads database to bloat up especially for SonarQube 7.x.

https://docs.sonarqube.org/latest/instance-administration/housekeeping/
https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L6

**What you expected to happen**:
* Users can specify their app version in each build and SonarQube uses it.
* SonarQube can clean up analysis data using housekeeping config.

**How to reproduce it**:
Execute massive amount of builds that have coverage config

**Comment by jithin1987** [comment]
cc @minz1027

**Comment by minz1027** [comment]
Use sha as projectVersion is just something nice to have so that you can track the analysis from the sonarqube UI by `sha`. But if it is affecting the house keeping, i guess we can just take it out. And if user wants to use that, they can always add it to their own config. @catto Does this seem ok? 

And for house keeping, you can also tune the config to delete the versioned ones, the default values are just way too long for large scale, we have tuned that internally already

**Comment by minz1027** [comment]
@catto checked their doc about data cleaning again and noticed that the clean is triggered when there is a new analysis. If the project is old and no one runs the build again, it stays forever. Same thing for PR projects since after the PR is merged, no new analysis will happen.

I found a way to bulk delete the old projects, Administration -> Projects, and you can pick the last analysis date and bulk delete the old projects.

**Comment by catto** [comment]
@minz1027 Seems ok to take projectVersion out 🙆
I think deleting manually via the UI you suggested is not better way since we have too many projects.
I also noticed the clean is triggered after each analysis. But for now it is fine that the clean runs for just active projects because their analysis run frequently, like tens per day, and database will soon bloat up by analyzed data.

**Comment by minz1027** [comment]
@catto i implemented the change and tested in cd.screwdriver.cd. For new sonar projects, it's working fine. But for existing projects, it's kinda confusing. Since existing projects has a `version` already, even the new analysis doesn't pass in the `projectVersion`, it inherits the current `version` which is the sha from the last run. This looks very confusing on the UI cuz all analysis will have that sha as version ever since. Clean up works fine with this, since only the latest analysis is versioned. It's just the UI very confusing.

Shall we just set `projectVersion` to `not provided`?

**Comment by catto** [comment]
@minz1027 Thank you for verification. I agree with you since it's actually confusing.
One thing better to consider is user-provided project version defined in sonar-project.properties.
If user defines project version in it, coverage bookend always overwrites the project version with `not provided`, so there is no way to provide version information by user.
Is it reasonable to parse sonar-project.properties and get projectVersion, then use it instead of `not provided` if user configured projectVersion?

**Comment by minz1027** [comment]
@catto yeah, makes sense to replace if user provides that! will add logic to parse it from  sonar-project.properties file
