### ISSUE TITLE
Shared image setting should not overwrite template image.

### ISSUE THREAD

**Issue by yokawara** [screwdriver-cd/screwdriver#1630]
### Context:
Even when users set `shared.image`, the setting should not overwite template images because a template usually has an image that works for its steps.
I think that current specification makes inconvenient to use `shared.image` setting and templates at the same time.

### What you expected to happen:
`shared.image` don't overwrite template image setting.
Images should be applied according to below priority:
job image > template image > shared image

**Comment by wahapo** [comment]
I think that other settings such as `environments` should prioritize shared settings over template settings. In this case, the sense of unity between the image and the environment disappears and it becomes difficult for users to understand. There are changes that affect users, but I think users cannot not keep up with this breaking changes. So we can also consider adding a more powerful parameter that is not overwritten with `shared.image`.
`sd-template.yaml`:
```
config:
  forceful-image: node:8
```

However, it is the best suggestion for me that the `config.image` setting in sd-template.yaml is stronger than `shared.image`.

**Comment by jithin1987** [comment]
I think current behavior makes more sense since it's a user provided config. User is explicitly saying I want to use this `image` and putting in shared is user's way of expressing that. 

Having `environment` alone not take precedence will only add to confusion of order.

Current order of template < shared < job makes  sense for users to reason easily about the order with which configs are applied to a job. It is more convenient also for users to put shared settings in `shared` without duplicating much.

**Comment by jithin1987** [comment]
User's playing around with an image which might not work is a real problem, but that is a direct result of openness of templates as a whole which enables this.

**Comment by yokawara** [comment]
I see, I agree with your opinion. 
And the inconvenient situation that I imagined might be not major one,  so we can close this ticket.
