### ISSUE TITLE
Support "--shallow-since" option for Git shallow cloning

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1641]
**What happened**:

For teams with large commits having "--shallow-since" option to compliment shallow clone depth will help. 

**What you expected to happen**:

Provide an environment variable to control "--shallow-since". This should override shallow clone depth setting and only one of them should be used

**How to reproduce it**:

https://docs.screwdriver.cd/user-guide/environment-variables#user-configurable

**Comment by jithin1987** [comment]
This is where fix should go https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L347

**Comment by okorz001** [comment]
For this to be useful, we need to have relative dates, e.g. 1 day ago, instead of absolute dates. As far as I am aware, git (2.21.0) does not currently support relative dates. I am looking into adding relative dates to git, but in the meantime I would like to add this to screwdriver.

What platforms does screwdriver run in? Can we assume GNU coreutils (date)? If we need platform portability, then I guess computing it in Javascript is the safest way.

**Comment by okorz001** [comment]
Actually git already supports this but it's just not well-documented. The underlying `approxidate` function used to parse --shallow-since into a unix timestamp supports relative times:
https://github.com/git/git/blob/83232e38648b51abbcbdb56c94632b6906cc85a6/t/t0006-date.sh#L100-L108

A relative date shallow clone can be like so: `$ git clone --shallow-since="8 weeks ago"`

I think screwdriver just needs to expose this `--shallow-since` parameter as an opaque value and let git handle it.
