### ISSUE TITLE
Feature request: support parallel fork join for remote jobs

### ISSUE THREAD

**Issue by updong** [screwdriver-cd/screwdriver#1710]
**What happened**:
I found out that I cannot use AND conditions on remote jobs 

```
"sd@223215:qa-minos-functional-test-us" fails to match the required pattern: /^~(sd@\d+:[\w-]+|(pr|commit|release|tag)(:(.+))?)$/,
```
and found out that SD doesn't support parallel fork join for remote jobs

**What you expected to happen**:
something like this. 

*A job which can wait for multiple remote job with AND condition*
```
  requires:
      - sd@123:A
      - sd@123:B
      - sd@456:C
      - sd@456:D
      - E
```
this job will wait for A B C D and E which runs in parallel and gets triggered when they're all successful.

**How to reproduce it**:
try adding remote job in requires field without `~`

**Comment by vnugopal** [comment]
@DekusDenial

**Comment by d2lam** [comment]
This can be implemented only if `sd@123:A, sd@123:B, sd@456:C, sd@456:D, E` all start from a single point, which will look like this:
![Image from iOS (2)](https://user-images.githubusercontent.com/3401924/65733140-1ee1de00-e082-11e9-91c1-04377fce7b37.jpg)

Without this constraint, it will get into race conditions & inconsistencies. For example, `sd@123:A` runs 1 week ago, `B,C,D,E` run now. Should `F` start or not? It's also almost impossible to implement since there is no way for `F` to track whether `A,B,C,D,E` finish in the same run because they can belong to different events. These events' end times can be within several minutes or several hours. How do we know which ones are supposed to be grouped together? This is probably why Jenkin's Join Plugin also relies on this constraint. 

I assume this was your intention as well since you mention `A B C D and E which runs in parallel ` @updong 

I can start with some design doc on how we implement this and people can review.

**Comment by updong** [comment]
@d2lam yes I forgot to mention about that constraint. yes I was assuming that constraint to be forced. then need to be triggered by same event.

**Comment by d2lam** [comment]
[WIP]
### DESIGN
Using the above example: `A -> [sd@123:A, sd@123:B, sd@456:C, sd@456:D, E] -> F`
Let's say A and F belong to `sd@789`

- After A is done, it figures the next jobs to run are `[sd@123:A, sd@123:B, sd@456:C, sd@456:D, E]` based on `sd@789` workflow graph. Let's say A's `eventId = 1`
- Trigger all these jobs in parallel with `upstreamEvent = 1`
- Trigger table will need to store these relationships since it is not captured by the external (sd@123, sd@456) workflow graph:
   - sd@123:A-> sd@789:F
   - sd@123:B-> sd@789:F
   - sd@456:C-> sd@789:F
   - sd@456:D-> sd@789:F
- Let's say `sd@123:B` finishes first. It first checks its next jobs from its own (`sd@123`)'s workflow graph. Then it will check the trigger table and finds out it needs to trigger `sd@789:F`
- Build the joinList for `sd@789:F`, which is derived by looking at its own workflow graph `(E)` AND the trigger table `sd@123:A, sd@123:B, sd@456:C, sd@456:D`
- It will then look at builds with `sd@123:B`'s upstreamEvent (`= 1`) and see if they all finish. 
- If not, create a build F with the same `eventId` as `upstreamEventId`
- If they are all finished, start build F

### TASKS
- Data-schema changes external trigger regex to accept `sd@pipelineId:jobname`
- Config-parser updated with new data-schema
- Workflow parser needs to handle `getNextJobs` and `getSrcFromJoin` accordingly
- API's build plugin handles new logic for join

**Comment by d2lam** [comment]
### DESIGN (REVISED 10/4/2019) 
The above implementation will work for backend. However, UI will need to query the trigger table to show each external nodes. Even though that's similar to what we are doing now, the current UI turns OFF displaying external triggers by default. With this feature implemented, we need to always have displaying external triggers turned ON. Otherwise, it will be very confusing to users. Therefore, I have revised the implementation design so that the load on the UI will not be too much. 

- workflow-parser now generates relationship to downstream jobs, in addition to the relationship in the yaml. 
- When each job finishes, it will figure out the next jobs. Since workflow graph now includes both internal & external edges, we can figure out next jobs by looking at the workflow graph. 
- Before each job starts, it needs to check the `joinList`. 
- When starting, it should store an additional field `upstream` in the form of `{ pipelineId: upstreamEventId}`. So that later it can merge back to the original event. 
- Figure out its `eventId` by traverse back to the original upstream event. 

### EXAMPLE & IMPLEMENTATION:
For example (current pipeline ID = 999): 
![Image from iOS (3)](https://user-images.githubusercontent.com/3401924/66240931-b8c50e80-e6b2-11e9-9ede-82e610aa81e0.jpg)

Previously, workflow graph will be:
```json
{
    "nodes": [
        { "name": "~pr" },
        { "name": "~commit" },
        { "name": "A" },
        { "name": "D" },
        { "name": "G" }
    ],
    "edges": [
        { "src": "A", "dest": "D" },
        { "src": "D", "dest": "G" }
    ]
}
```

Now, it should be:
```json
{
    "nodes": [
        { "name": "~pr" },
        { "name": "~commit" },
        { "name": "A" },
        { "name": "D" },
        { "name": "G" },
        { "name": "sd@111:B" },
        { "name": "sd@222:C" },
        { "name": "sd@333:E" },
        { "name": "sd@444:F" }
    ],
    "edges": [
        { "src": "A", "dest": "sd@111:B" },
        { "src": "A", "dest": "sd@222:C" },
        { "src": "A", "dest": "D" },
        { "src": "sd@111:B", "dest": "sd@333:E" },
        { "src": "sd@222:C", "dest": "sd@444:F" },
        { "src": "sd@333:E", "dest": "G", "join": true },
        { "src": "sd@444:F", "dest": "G", "join": true },
        { "src": "D", "dest": "G", "join": true }
    ]
}
```

To do this, we need to go pass in Trigger Factory from API -> config parser -> workflow-parser. Inside workflow parser, we compute the external nodes & edges by DFS traverse through each job's downstream jobs (look this information from the trigger table).

`getNextJobs` will now return both internal and external triggers:
- When A finishes, it will trigger `[sd@111:B, sd@222:C, D]`. 
- When `sd@111:B` finishes, it will trigger `[sd@333:E]`
.... 

Store `upstream` field to each build. It will look like this:
| job | eventID | upstream
|---| ---| --- |
| A | 1 | {} |
| G | 1 | {999:1} | 
| sd@111:B | 2 | {999: 1} |
| sd@222:C | 3 | {999:1} |
| sd@333:D | 4 | {999:1, 111:2} |
| sd@444:E | 5 |  {999:1, 222:3} | 
| E | 1 | {999:1, 111:2, 222:3, 333:4, 444:E} |

Before starting the next jobs, it should build the `joinList`. `joinList` can now be derived directly from the new workflow graph (instead of fetching the trigger table). The build's `eventId` can be computed by traversing the `upstream` field to the original event.

**Comment by d2lam** [comment]
- [ ] workflow-parser
- [ ] workflow-parser
- [ ] workflow-parser
- [ ] workflow-parser

**Comment by jithine** [comment]
This is now available https://blog.screwdriver.cd/post/611163633952735232/remote-join

**Comment by tkyi** [comment]
This feature is available in production.
Blog post: https://blog.screwdriver.cd/post/611163633952735232/remote-join
Docs: https://docs.screwdriver.cd/user-guide/configuration/workflow.html#remote-join
