### ISSUE TITLE
octokit/rest imports breaking change

### ISSUE THREAD

**Issue by sugarnaoming** [screwdriver-cd/screwdriver#1816]
**What happened**:
`octokit/rest` imports breaking change.
This change makes 'getRef' function unusable.
The version that imports this change is `16.34.0`.

**What you expected to happen**:
- pin `octokit/rest` version or version up GHE instance.

**How to reproduce it**:
- update octokit/rest version to `16.34.0`
- run acceptance test

**Comment by jithin1987** [comment]
how is this impacting us ? I see that https://beta.cd.screwdriver.cd/ is already on `16.34.0`

**Comment by jithin1987** [comment]
is this the reason why acceptance tests are failing in beta ? https://cd.screwdriver.cd/pipelines/1/builds/154432/steps/test

Seems like this should be a simple fix, once we figure out how api response changes.

This is the change in `octokit/rest` https://github.com/octokit/rest.js/commit/3933c24

**Comment by kumada626** [comment]
I think that this issue not cause acceptance tests failing in beta.

The URL of `getRef` changed in `octokit/rest` `16.34.0`.
https://github.com/octokit/rest.js/commit/e891d4e31c41e7a6afe0c8257404bf1f51607f5e#diff-0071a9eb9e809c9aacfc547f7514add6L1066
`github.com` supports also old and new URL, so it is not a matter if you use `github.com` as Screwdriver's scm.
However, if you use GithubEnterprise that does not yet support new URL as scm of Screwdriver.cd, `getRef` function will not be able to use.
Screwdriver.cd uses `getRef` function in `scm-github`.
https://github.com/screwdriver-cd/scm-github/blob/2117fd2548b5abfdec66f57b48af4f3f07597e2a/index.js#L666
This function is called when `tag` or `release` triggers webhook.
Therefore, `tag` and `release` triggered job will not be executed if you use  GithubEnterprise that does not yet support new URL as scm of Screwdriver.cd.
Furthermore, the acceptance tests on such Screwdriver.cd will fail.
Because we use `getRef` function in acceptance tests.
https://github.com/screwdriver-cd/screwdriver/blob/master/features/support/github.js
