### ISSUE TITLE
Trusted marks are disappeared from template/command list.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1857]
**What happened**:
Some templates/commands, which are marked trusted in their detail page, are not display trusted mark in the template/command list page(`UI_URL/commands` page).

**What you expected to happen**:
Trusted marks are correctly displayed in the template/command list page.

**How to reproduce it**:
1. Mark as trusted for templates / commands that have multiple versions published.
2. See template/command list page, template/command which is marked as trusted in 1. is not display trusted mark.

**Comment by ibu1224** [comment]
It was corrected to get the latest information with screwdriver-cd/datastore-sequelize#59. 
The trusted flag is added only to the oldest information, as shown in the following table. 
```
+-------+---------+--------------------------+---------+
| id    | version | createTime               | trusted |
+-------+---------+--------------------------+---------+
|  1    | 0.0.0   | 2018-09-06T01:11:11.111Z |       1 |
|  2    | 0.0.1   | 2018-09-07T02:22:22.222Z |    NULL |
|  3    | 0.0.2   | 2018-09-08T03:33:33.333Z |    NULL |
+-------+---------+--------------------------+---------+
```

The modified query is getting the latest template information.
However, if trusted is null, it cannot be acquired correctly.
Therefore, it is not enough to get the latest information.


I propose three solution.

1. Apply to all versions when trust is manipulated.  
I think it is inefficient for templates and commands with many versions.

2. Create a new `trusted` table.  
This is an ideal implementation,However there are many fixes.
I don't recommend it now because I want to fix it quickly.
We need to think this problem.

3. Change SQL only in trusted.
This is not an ideal implementation.   
However,I recommend it because there are few modifications.

We think plan 3 is a good idea in the short term.
Therefore, we want to implement it in plan 3.

@jithine What do you think?

**Comment by jithine** [comment]
@ibu1224 Does 3 means that we have to query twice to determine whether template/command is trusted ?

Can we handle this when creating a template/command ? ie carry over value of trusted from earlier version ? but we will have to do a data migration to fix existing entries.

**Comment by ibu1224** [comment]
@jithine 
I don't think need to query twice. 
There are ideas to implement with queries, but I don't know if they can be implemented with `datastore-sequelize`.

As written, it seems to pull from the existing version.

**Comment by jithine** [comment]
@ibu1224 can you elaborate option 3 ? I am not clear what does it entail.

**Comment by ibu1224** [comment]
@jithine
I'm sorry, there was not enough explanation.

The idea to implement with a single query.
The current query is as follows:
```
select
    templates.id,
     ...
    templates.trusted
  from templates
  left join templates as t on (
    templates.name = t.name
    and templates.namespace = t.namespace
    and templates.id < t.id
  )
  where t.id is null;
```
If `trusted` is null, this query is not retrieved .
However, `trusted` worked with queries using MAX.
Therefore, left join `trusted` to the above query.

That way, the query is one time.

**Comment by DekusDenial** [comment]
@ibu1224 @kumada626  sorry, late to the discussion, but since the change introduced in https://github.com/screwdriver-cd/datastore-sequelize/pull/59 involves subquery (which was something I was not too fond of and had slight concern about cuz it complicated things with ORM and the modular nature the codes were written in).

Now why dont we combine aggregation and subquery altogether which should fix the `version` due to sql's lexicographic nature on text. IIRC, the original intent for casting `trusted` as integer is to have the aggregate function `max` works well with it since this column is simply binary.

Also, undergoing some local testing on postgresql, it seems the new query proposed in https://github.com/screwdriver-cd/screwdriver/issues/1723 is an order of magnitude slower perhaps due to its subquerying so this is just something off of top of my head...

```sql
SELECT
  MAX("name") AS "name",
  MAX("version") AS "version",
  MAX("namespace") AS "namespace",
  MAX("latest"."ct") AS "createTime",
  MAX(CAST("trusted" AS INTEGER)) AS "trusted"
FROM
  (
    SELECT
      "namespace" AS "ns",
      "name" AS "n",
      MAX("createTime") as "ct"
    FROM
      "templates"
    GROUP BY
      "ns",
      "n"
  ) as "latest"
  INNER JOIN "templates" ON "templates"."namespace" = "latest"."ns"
  AND "templates"."name" = "latest"."n"
  WHERE "templates"."createTime" = "latest"."ct" OR "templates"."createTime" is null
GROUP BY
  "namespace",
  "name"
ORDER BY
  "createTime" DESC NULLS LAST;
```

This is very close/similar to the `option 3` from https://github.com/screwdriver-cd/screwdriver/issues/1723 as well.

**Disclaimer: I am not sure how the above sql snippet will perform in MySQL**

**Comment by ibu1224** [comment]
@DekusDenial 
Thank you! We wanted to do it.
The above SQL doesn't work with MYSQL, therefore I translated it.

#### Sample template data

| name | namespace | version | trusted |
| ------------- | ------------- | ------------- | ------------- |
| foo  | bar  | 0.0.9| 1 |
| foo  | bar  | 0.0.10 | NULL |


#### SQL
```
SELECT
  MAX(name) AS name,
  MAX(version) AS version,
  MAX(namespace) AS namespace,
  MAX(CAST(trusted AS SIGNED)) AS trusted
FROM
  (
    SELECT
      namespace AS ns,
      name AS n,
      MAX(createTime) as ct
    FROM
      templates
    GROUP BY
      ns,
      n
  ) as latest
  INNER JOIN templates ON templates.namespace = latest.ns
  AND templates.name = latest.n
  WHERE templates.createTime = latest.ct OR templates.createTime is null
GROUP BY
  namespace,
  name
ORDER BY
  createTime DESC NULLS LAST;
```
#### Result 
| name | namespace | version | trusted |
| ------------- | ------------- | ------------- | ------------- |
| foo  | bar  | 0.0.9| 1 |

This query is not getting the last updated value.
My ` postgresql` ` mysql` translation may not be working.

**Comment by DekusDenial** [comment]
@ibu1224 just to make sure identical queries are run on both psql and mysql, i have set up my local mysql  w/ production dump along with the same on my local psql and ran the following queries on both respectively:

```sql
SELECT
  MAX(name) AS name,
  MAX(version) AS version,
  MAX(namespace) AS namespace,
  MAX(latest.ct) as createtime,
  MAX(latest.td) as trusted
FROM
  (
    SELECT
      namespace AS ns,
      name AS n,
      MAX(createTime) AS ct,
      MAX(CAST(trusted AS SIGNED)) AS td
    FROM
      templates
    GROUP BY
      ns,
      n
  ) as latest
  INNER JOIN templates ON templates.namespace = latest.ns
  AND templates.name = latest.n
  WHERE templates.createTime = latest.ct OR templates.createTime is null
GROUP BY
  namespace,
  name
ORDER BY
  createTime DESC;
```

and the equivalent in psql:

```sql
SELECT
  MAX("name") AS "name",
  MAX("version") AS "version",
  MAX("namespace") AS "namespace",
  MAX("latest"."ct") AS "createTime",
  MAX("latest"."td") AS "trusted"
FROM
  (
    SELECT
      "namespace" AS "ns",
      "name" AS "n",
      MAX("createTime") AS "ct",
      MAX(CAST("trusted" AS INTEGER)) AS "td"
    FROM
      "templates"
    GROUP BY
      "ns",
      "n"
  ) as "latest"
  INNER JOIN "templates" ON "templates"."namespace" = "latest"."ns"
  AND "templates"."name" = "latest"."n"
  WHERE "templates"."createTime" = "latest"."ct" OR "templates"."createTime" is null
GROUP BY
  "namespace",
  "name"
ORDER BY
  "createTime" DESC NULLS LAST;
```

and i was able to get the latest version (there is only one version filtered by latest inside the inner subquery) as well as the correct value for trusted (also attained from the inner subquery). Though, this is not the prettiest thing in the world but it does satisfy for the best of both worlds. Honestly, i don't know what's the most elegant way to translate and sequelize the query...

**Comment by ibu1224** [comment]
@DekusDenial 
Thank you for introducing the nice query.
However, the query could not get the latest version.
Therefore, we thought the following query:
```
SELECT
  *
FROM
  (
    SELECT
      *
    FROM
      templates
    WHERE
      templates.id IN (
        SELECT
          MAX(t.id)
        FROM
          templates AS t
        WHERE
          templates.name = t.name
          AND templates.namespace = t.namespace
          AND templates.id <= t.id
      )
    ) as latest
  INNER JOIN 
  (
    SELECT
      namespace AS ns,
      name AS n,
      MAX(createTime) AS ct,
      MAX(CAST(trusted AS SIGNED)) AS td
    FROM
      templates
    GROUP BY
      ns,
      n
  ) as td
  ON td.n = latest.name
  AND td.ns = latest.namespace;
```
This query got all the latest values.
What do you think?


> FYI, the templates query currently running in the latest screwdriver-api today took > 4 secs to complete on our production.

We want to know the environment of this result.
Is it the result of making the production environment data into a dump file and executing it locally?

**Comment by DekusDenial** [comment]
@ibu1224 sorry still have trouble understand what caused you not able to get the latest query as the query, like I explained above, should really work and also I think `id` and `createTime` should be interchangeable as they convey and are used similarly. So if you can alter my query a little bit and filter on the max(id) instead of createTime, that may be the different, but who knows...

I have to run your query tomorrow to see analyze the difference.

> We want to know the environment of this result.
Is it the result of making the production environment data into a dump file and executing it locally?

No, the query was run directly on our production psql db. But the performance results are consistent on both local and real production testings. Also, I would like to know the query performance on your side on your Percona MySQL. Thanks

**Comment by yoshwata** [comment]
@DekusDenial  This issue comment might be help.
https://github.com/screwdriver-cd/screwdriver/issues/1723#issuecomment-539314438

The performance in our production environment is this.
```
735 rows in set (0.44 sec)
```

Out production environment has 6450 templates now.
```sql
mysql> select count(id) from templates;
+-----------+
| count(id) |
+-----------+
|      6450 |
+-----------+
1 row in set (0.22 sec)
```

**Comment by yoshwata** [comment]
I make a PR, but it's now **Work In Progress**.
https://github.com/screwdriver-cd/datastore-sequelize/pull/63

That's SQL query is like this, and this can show correct trusted information, version and description.
```sql
SELECT
  id,
  name,
  version,
  namespace,
  (
    SELECT
      MAX(trusted)
    FROM
      templates
    WHERE
      t1.name = name
      AND t1.namespace = namespace
  ) AS trusted
FROM
  templates AS t1
WHERE
  t1.id IN (
    SELECT
      MAX(t2.id)
    FROM
      templates AS t2
    WHERE
      t1.name = t2.name
      AND t1.namespace = t2.namespace
      AND t1.id <= t2.id
  )
ORDER BY
  createTime;
```

We will make a test for this code, so now it's still work in progress.

**Comment by DekusDenial** [comment]
@yoshwata @ibu1224 

> @DekusDenial This issue comment might be help.
> [#1723 (comment)](https://github.com/screwdriver-cd/screwdriver/issues/1723#issuecomment-539314438)
> 
> The performance in our production environment is this.
> 
> ```
> 735 rows in set (0.44 sec)
> ```
> 
> Out production environment has 6450 templates now.
> 
> ```sql
> mysql> select count(id) from templates;
> +-----------+
> | count(id) |
> +-----------+
> |      6450 |
> +-----------+
> 1 row in set (0.22 sec)
> ```

So I borrowed the example from your comment.

| namespace | name | description | version
----|---- |---- |---- |
| foo | bar | 2 | 0.0.10
| foo | bar | 1 | 0.0.9
| foo | bar | 9 | 0.0.8

and insert the followings into my local mysql

```sql
INSERT INTO screwdriver.templates VALUES ( 16850, NULL, NULL, 'foo', '0.0.8', '9', NULL, NULL, 'bar', NULL, '2019-12-10T01:03:56.111Z', NULL );
INSERT INTO screwdriver.templates VALUES ( 16851, NULL, NULL, 'foo', '0.0.9', '1', NULL, NULL, 'bar', NULL, '2019-12-10T01:03:56.222Z', 1 );
INSERT INTO screwdriver.templates VALUES ( 16852, NULL, NULL, 'foo', '0.0.10', '2', NULL, NULL, 'bar', NULL, '2019-12-10T01:03:56.333Z', NULL );
```

and ran my query

```sql
SELECT
  MAX(name) AS name,
  MAX(version) AS version,
  MAX(namespace) AS namespace,
  MAX(description) AS description,
  MAX(latest.ct) as createtime,
  MAX(latest.td) as trusted
FROM
  (
    SELECT
      namespace AS ns,
      name AS n,
      MAX(createTime) AS ct,
      MAX(CAST(trusted AS SIGNED)) AS td
    FROM
      templates
    GROUP BY
      ns,
      n
  ) as latest
  INNER JOIN templates ON templates.namespace = latest.ns
  AND templates.name = latest.n
  WHERE templates.createTime = latest.ct OR templates.createTime is null
GROUP BY
  namespace,
  name
ORDER BY
  createTime DESC;
```
and my result is:

| name  | version | namespace | description | createtime | trusted |
| - | - | - | - | - | - |
| ... | ... | ... | ... | ... | ... |
| foo | 0.0.10 | bar | 2 | 2019-12-10T01:03:56.333Z |  1 |
| ... | ... | ... | ... | ... | ... |

and to give you about the mysql environment on the templates table (just a subset of the existing prodution)

```sql
mysql> select COUNT(*) from templates;
+----------+
| COUNT(*) |
+----------+
|    15940 |
+----------+
1 row in set (0.01 sec)
```

and running the latest query from screwdriver-api today will give this:

`367 rows in set (0.94 sec)`

and result from my proposed query is:

`367 rows in set, 2 warnings (0.08 sec)`

All I can say at the end here is to make sure we are not going in a worse direction jeopardizing the performance, even if this is just a query for only a small subset of the application. Nonetheless, I really appreciate your other PR to add subquery to sequelize, which is something I don't feel comfortable doing because this means we actually admit and realize the need for more abstraction on the db/api side so we are not governed by the ORM and this is potentially conclusive enough that the way we do db query layer is wrong.

I personally rather believe in a separate well-defined connector than a mis-abstracted plugin, if you know what i mean. 😅

**Comment by yoshwata** [comment]
@DekusDenial Thank you. We noticed that your query works fine, and the course of your query don't work in our environment is many 'NULL' value in the 'createtime' column.

After all, we cannot find the way to make sub-query of 'FROM' clause for 'INNER JOIN' with sequelize. Instead of using 'INNER JOIN', we found another way of sequelize to same functionality by sub-query of 'SELECT' field. This is the [PR](https://github.com/screwdriver-cd/datastore-sequelize/pull/63).

> Nonetheless, I really appreciate your other PR to add subquery to sequelize, which is something I don't feel comfortable doing because this means we actually admit and realize the need for more abstraction on the db/api side so we are not governed by the ORM and this is potentially conclusive enough that the way we do db query layer is wrong.

The [PR](https://github.com/screwdriver-cd/datastore-sequelize/pull/63) is to fix the list screen of Templates/Commands for the moment. Basically I agree to more abstracted interface, and that is the issue that should be solved with stepwise.

**Comment by DekusDenial** [comment]
> @DekusDenial Thank you. We noticed that your query works fine, and the course of your query don't work in our environment is many 'NULL' value in the 'createtime' column.

Ok, but you can interchange it with `id` which should theoretically work the same way, only with a bit more clarity in the query.

> Basically I agree to more abstracted interface, and that is the issue that should be solved with stepwise.

yeah, it appears to be a fundamental problem if you think about it.

**Comment by jithine** [comment]
Changes are available in https://cd.screwdriver.cd/templates
