### ISSUE TITLE
npm request package has been deprecated

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1961]
**What happened**:
https://www.npmjs.com/package/request
> request has been deprecated, see https://github.com/request/request/issues/3142

**What you expected to happen**:
We need alternative package.

Reference: https://github.com/request/request/issues/3143

**Comment by tkyi** [comment]
I think this package is created by the same person as the new alternative: https://github.com/mikeal/bent
Might be an easier transition?

**Comment by tk3fftk** [comment]
> I think this package is created by the same person as the new alternative: https://github.com/mikeal/bent

It looks nice. My concern is it a little outdated (last commit is 9 months ago)

[axios/axios](https://github.com/axios/axios) is looks popular alternative but the version is still under `1.0.0` so there are possibility of breaking changes.
I take a glanced at [sindresorhus/got](https://github.com/sindresorhus/got), it provides migration guide from `request`.
https://github.com/sindresorhus/got/blob/main/documentation/migration-guides.md

**Comment by adong** [comment]
Just a thought: rather than just swapping the `request` library, can we use this opportunity to have a thin layer build on top of the yet-to-choose library? In that case, we could just swap the code underneath it and leave the high-level code untouched, in case we need to do it again a few years down the road. 🤔
