### ISSUE TITLE
[~release] trigger works on the latest commit only

### ISSUE THREAD

**Issue by edudar** [screwdriver-cd/screwdriver#1969]
**What happened**:
Making a release in GitHub UI for any of the previous commits triggers a build that fails to check out sources with a message like the following:
```
Remote branch f586d4eab01e0bdc43aac547495d25f7d9c96562 not found in upstream origin
```
`[~tag]` trigger works, however. Comparing what is the difference, it looks like `[~tag]` works pretty much the same way as `[~commit]` and checks out `master` but `[~release]` actually tries to check out SHA-named branch.

**What you expected to happen**:
`[~release]` triggers a build and succeeds on past commits

**Comment by jithine** [comment]
cc @screwdriver-cd/yahoo-japan

**Comment by yoshwata** [comment]
@edudar I could not reproduce it. Release trigger checkouts sha that the tag points to. 

Could you check this problem occurs again?

If it occurs please tell me the procedure to reproduce it, what I'm concerning are below.
- How is your screwdriver.yaml?
- What branch your pipeline pointing?
- How do you push tags?

**Comment by andreisidorenko** [comment]
@yoshwata the procedure to reproduce it(through github ui):
- Click on "Draft new release" in releases section
- use new tag version and choose not "branches section", but "Recent Commits" with some commit
<img width="521" alt="Screen Shot 2020-07-27 at 15 51 17" src="https://user-images.githubusercontent.com/59011539/88544093-8b6e9600-d021-11ea-81cd-cec9088c4530.png">

And when you create release, sd-setup-scm uses in GIT_BRANCH this commit hash, that's why we have an error `fatal: Remote branch 3d3144e... not found in upstream origin`

If we use existing tags and choose branch in "branches section" - all work, but it should work also in the first case.

How is your screwdriver.yaml? - no matter, any
What branch your pipeline pointing? - no matter, tested on few
How do you push tags? -  to reproduce it - create tag through Github UI on create release step

CC: @jithine
