### ISSUE TITLE
First PR job includes adding screwdriver.yaml won't run

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#2094]
**What happened**:
We found a behavior change. It may be caused by [this change](https://github.com/screwdriver-cd/models/pull/449/files).
We think there is a flow of a use case:
1. create a new repository without screwdriver.yaml
1. do first implementation on other branch
1. create a pipeline of the repository
1. open a new PR about the implementation including screwdriver.yaml to run first PR job
1. review the PR, is the code good? and is CI(Screwdriver.cd job) passed? ...

Currently, we cannot use this flow. The first PR job won't run.
Previously, absent of screwdriver.yaml on the pipeline branch was ignored in `pipeline.sync()` so a PR job would run if the PR adds screwdriver.yaml.

There is an another issue. When we do this step:
> 3. create a pipeline of the repository

First time to push the button on UI to create a pipeline, UI shows an error after showing loading icon for a long time. It may fail `pipeline.sync()` due to absent of screwdriver.yaml.
Second time to push the button, it looks success creating a pipeline. But it would be just a redirection.

**What you expected to happen**:
Run a first PR job which includes adding screwdriver.yaml to a repository.

**How to reproduce it**:
1. create a repository without screwdriver.yaml
1. create a pipeline of the repository (an another error will also happen, so we need to press button twice)
1. create a new branch to add screwdriver.yaml and open a new PR
1. run `PR sync` on screwdriver.cd then a PR job will be created but will not run yet
1. close/reopen the PR (or sync pipeline)
1. the PR job won't run and the PR job will be removed

workaround: create an empty screwdriver.yaml on a pipeline branch.

Related: https://github.com/screwdriver-cd/models/pull/449

**Comment by jithine** [comment]
This is a tricky problem to solve, reason I made that an error was to solve this problem.

1. Period build starts.
2. Fetching `screwdriver.yaml` fails due to GHE connection error. Randomness and most likely will pass in next run.
3. With out the error, `config-parser` returns a generic config and overwrites job configs. https://github.com/screwdriver-cd/config-parser/blob/master/index.js#L86-L109
4. Periodic jobs looses config and stops working. user has to manually do pipeline sync.

So what we need  is a flow which combines both these scenarios.

**Comment by tk3fftk** [comment]
Related(mentioned as `an another issue` in my issue): https://github.com/screwdriver-cd/screwdriver/issues/2104
