### ISSUE TITLE
Timeouts from logservice to SD API & Store

### ISSUE THREAD

**Issue by parthasl** [screwdriver-cd/screwdriver#2106]
**What happened**:

We are observing frequent timeouts from log service calls to API & Store, also observed that connections from log service are not closed properly.

**What you expected to happen**:

log service API calls to API & Store must terminate and clean up properly.

**How to reproduce it**:

**Comment by sakka2** [comment]
This issue also and still happens in our environment though we had already merged this patch.
We are investigating the reason of this issue, but now we have no idea.
So, could you share the detail of circumstances at that time and cause of this problems?

**Comment by jithine** [comment]
What we observed was we are having build failures because launcher & log-service tries to update API & log-service, they don't get response back in time goes into retry mode. Sometimes it works on retry but sometimes it never recovers. Our findings are following

1. Could be a bug in hyperd where pod looses network connections and is unable to make any external calls.
1. When logservice entered retry mode it was not closing connections. And has hardcoded 20s timeouts. But Store API had a default timeout of 2mins when talking to S3. So we had this PR https://github.com/screwdriver-cd/store/pull/102 to configure that in store level and then to match it with logservice timeouts.
https://docs.screwdriver.cd/cluster-management/configure-build
1 Moving to Kata containers will solve these issues, because we believe it's caused by bugs in Hyperd.

**Comment by sakka2** [comment]
Thanks for reply! 
We understand it.
We are going to move Kata containers asap!

**Comment by kkisic** [comment]
For the following environment variables added in this issue, the guide says they are available when we set them by executors. 
However, there does not seem to be a place for them to be set at any executors.
