### ISSUE TITLE
UI - List view does not scroll

### ISSUE THREAD

**Issue by brian65535** [screwdriver-cd/screwdriver#2181]
**What happened**:
Screwdriver UI **list view** does not scroll in some browsers. When a pipeline has more jobs than a list view area can show, users should be able to scroll down the list view and the UI show load more jobs into the view area.

But scrolling in **list view** does not work in some browsers:
- Chrome 84.0.4147.125
- Firefox 68.11.0esr

And no scrolling issue in
- Firefox 79.0

When the issue happens, a workaround to make scrolling work again is to resize down the browser window so that jobs cannot fit in the view area and a scrollbar show up. Once the vertical scrollbar show up, scrolling works fine.

**What you expected to happen**:
Scrolling should work in the first place in all browsers without resizing the window.

**How to reproduce it**:

**Comment by adong** [comment]
This is an issue in ember-light-table version 2.x beta, need to take a deep look

**Comment by adong** [comment]
I checked out the https://github.com/screwdriver-cd/ui/commit/32d16fa559dac66f8f064a8e45d5a557a0b75a18 before we upgrade `ember-light-table` from 1.x to 2.x, and I found the following:

`ember-light-table@1.13.2` was using 

```
    "ember-scrollable": "^0.5.0",
    "ember-in-viewport": "~3.0.3",
```


while `ember-light-table@2.0.0-beta.5` was using 

```
    "ember-scrollable": "^1.0.0",
    "ember-in-viewport": "^3.5.8"
```


It appears to be an issue related to https://github.com/offirgolan/ember-light-table/pull/693


Ref: 
1) https://github.com/DockYard/ember-in-viewport/issues/186



PS: I do see why it is `height="inherit"` in

```
{{#light-table table height="inherit" as |t|}}
```

because the older version's CSS property is `height: inherit`.
![image](https://user-images.githubusercontent.com/15989893/90195170-a1988800-dd7d-11ea-8525-dad7a720bcd9.png)
