### ISSUE TITLE
Screwdriver to add webhooks

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#219]
When I create a new pipeline in Screwdriver, I expect the service to add the correct webhooks to my repository.

**Comment by stjohnjohnson** [comment]
Hmm, due to security restrictions here: https://developer.github.com/v3/orgs/hooks/

> In order to protect sensitive data which may be present in webhook configurations, we also enforce the following access control rules:
> - OAuth applications cannot list, view, or edit webhooks which they did not create.

I don't think we can determine if someone has setup an organizational webhook for Screwdriver already.  I also can't tell if they will send duplicate events if you setup in both places: https://developer.github.com/webhooks/

Anyway, what this boils down to is we should probably just add the webhooks to the repo level and ask people not to use org webhooks. :(

API details: https://developer.github.com/v3/repos/hooks/#create-a-hook

**Comment by FenrirUnbound** [comment]
Org webhooks are incredibly convenient. It's a one-time setup and the team gets all the benefits without further configuration changes.

What about allowing an opt-in for repository-specific webhooks?

**Comment by d2lam** [comment]
Keeping track of this in https://github.com/screwdriver-cd/screwdriver/issues/379
