### ISSUE TITLE
Make notification validation a warning

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2339]
**What happened**:

Notification validation is an error today which is causing a problem for existing users who already have wrong config in their `screwdriver.yaml`

**What you expected to happen**:

1. Provide a feature flag environment variable `NOTIFICATIONS_VALIDATION_ERROR` to control this behavior
2. `NOTIFICATIONS_VALIDATION_ERROR` should be `true` by default
3. `NOTIFICATIONS_VALIDATION_ERROR=true` means current behavior, `config-parser` error on validation 
4. `NOTIFICATIONS_VALIDATION_ERROR=false` means `config-parser` warning on validation

**How to reproduce it**:
Try running an existing pipeline with validation error

**Comment by jithine** [comment]
cc @ibu1224 @kumada626

**Comment by tkyi** [comment]
Now when you set `NOTIFICATIONS` as:
```
{
  "options": {
    "throwValidationErr": false
  },
	"slack": {
		"token": "xoxb-sometoken"
	}
}
```
Builds should not fail for notifications issues, and you should get a warning instead of an error:
<img width="1150" alt="Screen Shot 2021-02-10 at 2 21 41 PM" src="https://user-images.githubusercontent.com/3230529/107580451-6dc2e180-6bab-11eb-86d5-84b8cdcd25d5.png">
