### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2369]
**What happened**:
It would be nice to have a desktop notification when all event builds are complete.

**What you expected to happen**:
This can be implemented by using https://pushjs.org/ , for example.

**How to reproduce it**:

**Comment by yakanechi** [comment]
Since there was a need for this functionality, I am proposing two types of modifications.

1. Push notification from the browser when the status of the pipeline screen is changed to completion, error, etc.
    - Advantages
      - Very easy to implement.
      - Only one button to turn on/off push notifications is needed on the user's settings screen.
    - Disadvantages
      - The user must keep the pipeline screen that he/she wants to receive notifications from open in the browser. However, this is not such a big issue since it can be opened in a separate tab.
      - Notification timing is not completely real-time as it depends on the frequency of UI updates. 2.

2. Push notification from API using ServiceWorker
    - Advantages
      - Convenient for users as they will be notified even if they are not viewing the pipeline screen, etc. On the other hand, it is necessary to change the DB for key management, etc.
    - Disadvantages
      - DB needs to be modified to manage destination endpoints and public keys, which can lead to large scale changes.
      - Also, the DB must be searched when a build is completed, which may put a burden on the DB.

I am suggesting two options, but in practice I recommend the first.

Push notifications are intended to be used in casual pipelines, such as testing and behavior checks, where it is not necessary to add configuration to yaml.
Since notifications are already implemented in Slack, etc., I have decided that it is not a feature that would put too much load on the DB or anything like that.

**Comment by tanoda** [comment]
These days, some browsers may unload the inactive (background) page. So the first option's first disadvantage might be severe.

**Comment by yakanechi** [comment]
After checking, it may be possible to work around it in Chrome with settings such as Calculate window occlusion on Windows.
However, it is undesirable to force users to accept a browser-wide performance degradation. 
Also, other browsers do not have the same workaround.
Proposal 1 seems to be deprecated because it is incompatible with current browsers.

**Comment by yakanechi** [comment]
@tanoda
The team decided to recommend plan 1.
The idea is that 2 would duplicate the role of other functions such as Slack and email, and that it is not enough of a feature to make changes to the DB as a need for Push notifications.
Although there are some problems, we decided that the problem can be avoided by user operation, although it may put some burden on the users, such as leaving them at the edge of the sub-display in the case of multiple displays.

**Comment by tanoda** [comment]
Alright, no problem at all. I was just letting you know that the workaround is not very good these days.
It's good that you decided on it with updated pros/cons.
