### ISSUE TITLE
Private pipeline's code can be seen via SonarQube project.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2520]
**What happened**:
The code in the private pipeline should not be seen by anyone other than permitted users.
However, if the private pipeline use coverage feature, Screwdriver sends the private pipeline's code to SonarQube.
Since SonarQube project's permission is not linked to scm's permission, the private pipeline's code can be seen by not permitted users on the scm via SonarQube project.

**What you expected to happen**:
Private pipeline's code should not be sent to SonarQube.
If users want to use SonarQube anyway, users add force enable flag for example.

**How to reproduce it**:

**Comment by jithine** [comment]
I think projects in sonarqube's permission can be controller, we might be making it public for all. Need to handle separately for private repositories. 

cc @tkyi

**Comment by tk3fftk** [comment]
I took a look at GitHub integration of SonarQube.
There is an option to sync GitHub teams in an organization with SonarQube groups.
![image](https://user-images.githubusercontent.com/3445553/128321815-46dd0760-44ea-41cf-8a74-a897538d2a62.png)
(It looks that there is not detailed information in the document about [`Group Mapping`](https://docs.sonarqube.org/latest/instance-administration/delegated-auth/) with GitHub.)

This feature has some limitations:
- We have to use GitHub authorization.
- User have to use GitHub organization and GitHub teams to join SonarQube groups automatically.
- In SonarQube, admin have to create groups named in the form of `Organization/Team`.
- I don't know how to sync permissions of GitHub org/teams especially including private repositories with corresponding SonarQube groups. It looks just adding users to groups.

**Comment by jithine** [comment]
@tk3fftk I don't think we should do any sync. 

All we can do is when creating a sonarqube project we can mark it as private if Git repository is private. But we can't do anything for existing projects, maybe an offline script to adjust permissions.

**Comment by jithine** [comment]
It's not possible to prevent scanner from sending coverage info, since coverage calculation happens on sonar server. This is the response we got from SonarQube support as well. 
```
It is not possible to avoid source code to be sent to SonarQube, the reason is the way analysis is done.

Let me explain you that.

On the scanner side the scanner runs the analysis and raises issues, then a report is created and sent to SonarQube.

This report contains sources, issues, coverage informations, etc...

Then this report is consumed by a background task to match issues with sources, coverage with sources, etc... many metrics are computed at this time.

So for that reason it is not possible to avoid source code to be sent to SonarQube.

However, inside SonarQube you can restrict the access to the source code to whoever you want.

For example, the private code is modified by some devs and maybe a project manager is supervising it. Then you can restrict the view of this source code only to those individuals. simply remove the browse permission at project level and grant only the desired persons for that.
```

**Comment by ibu1224** [comment]
@jithine @kumada626  and everyone

I have come up with a first step to resolve this Issue. Please let me feedback.
As soon as we get agreement, we will proceed to development.

The current system may cause source code to be sent to SonarQube without the user's intention.
For example, If you are using sd template and the default `SD_COVERAGE_PLUGIN_ENABLED` is true. 

Therefore, if you are using a private repository, do not send the source code until you find a solution.
Below are some ideas to achieve this.

## 1. Create a flag that allows you to determine that it is private repository.
Where should flags be managed? (Metadata? Env?) I think it should be managed by environment variables.

The reason is that Metadata can be overwritten by users. In the case of `~PR,` malicious users may be able to overwrite the metadata.
In the case of environment variables, the [readonly](https://pubs.opengroup.org/onlinepubs/009695299/utilities/readonly.html) command can be used to prevent overwriting. readonly is available in most shells.

By modifying the following part, it can be managed by environment variables.

- Environment variables are set in [launch.go](https://github.com/screwdriver-cd/launcher/blob/f33e27e5f7d812c73286c6f1fdaf3ff40c9a437d/launch.go#L597-L635).
  - add new environment variables to this list. (ex: `SD_PRIVATE_REPOSITORY`)
  - You can tell if it is private by contacting the API. This is already implemented.
    - [Get pipeline objects](https://github.com/screwdriver-cd/launcher/blob/f33e27e5f7d812c73286c6f1fdaf3ff40c9a437d/screwdriver/screwdriver.go#L407-L423). [pipeline objects](https://api.screwdriver.cd/v4/documentation#/v4/getV4PipelinesId).  

## 2. The flag created above is used in the [coverage-sonar](https://github.com/screwdriver-cd/coverage-sonar).
For private repositories, skip communication to SonarQube.

Modify as follows.
- Add private flag determination to [commands.txt](https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt).

Again, this means that SonarQube is still not available in the Private repository. We will need to think about this in the future.

However, by implementing this, the source code in the Private Repository will no longer be submitted.

**Comment by ibu1224** [comment]
@jithine @tkyi @kumada626 and everyone
I have modified [my comment](https://github.com/screwdriver-cd/screwdriver/issues/2520#issuecomment-1092594858) in the feedback at `yj`.
Please see again.
