### ISSUE TITLE
[Feature Request] Does not overwrite PR comment that from other PR job

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2695]
**What happened**:
If there are multiple PR builds and they are making PR comments to each other, the PR comment will be overwritten by jobs that finish later.

**What you expected to happen**:
PR comment only overwrite comment that from the same PR job.

**How to reproduce it**:
1. Define multiple PR jobs and set `meta.summary` in the build to each other.
2. Make a Pull Request and start PR builds.
3. Only single PR comment(overwritten by jobs that finish later).

**Comment by ibu1224** [comment]
@jithine @tkyi @kumada626 and everyone

I have been trying to think of ways to add this feature.
Please give me feedback. Once consent is obtained, the development can be done.

The current PR comments work as follows. ([`addPrComment`](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L1671-L1722))
- Communicate with GitHub to retrieve PR comments.
- If the PR comment exists and has been written by a bot, overwrite the comment. If not, create a new PR comment.

In other words, if there is a bot comment on the PR, it is overwritten.

Therefore, to create PR comments in multiple PR builds, it is necessary to determine which job the PR comments were written for.

Here is the solution I have come up with.

## Solution 1. Add `jobId` to PR comments.

Add the `jobId` to PR comments, and when a comment is retrieved from GitHub, parse the contents of the comment to determine which job wrote it.  

<img width="918" alt="add_jobId" src="https://user-images.githubusercontent.com/17828065/167778237-50b3a1ae-7b4d-4159-aec4-29b00806a317.png">


Modify the following sections.

- Prepare `jobId`
  - Fortunately, `jobId` is readily available. It is resolved in [`updateCommitStatus`](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L286-L352), which calls [`addPrComment`](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L1671-L1722).
    - Add `jobId` to [`prConfig`](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L317-L323).
      - Now you can use `jobId` in `addPrComment`. 
- Parse the `jobId` in the PR comment.
  - We already have the ability to retrieve PR Comments from GitHub.[prComments](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L1677)
  - The body of the PR comments obtained is parsed to determine if the `jobId` matches.
    -  If the `jobId` matches, you can overwrite it, otherwise you can create a new one.
    - The function to [overwrite](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L376-L396) and the part to make [new comments](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L1700-L1710) have already been implemented.
- Write `jobId` in PR comments.
  - PR comments are formatted in [`getPrComment`](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L137-L153) and sent to [`addPrComment`](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L1671-L1722).
    - Pass the `jobId` to getPrcomment and include the `jobId` in the comment.



## Solution 2. Get the `buildId` written in the PR comments and the `jobId` using the Screwdriver API.
Same as `Solution 1`. making the `jobId` available in [`addPrComment`](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L1671-L1722). The difference is that the `jobId` is obtained from the Screwdriver API using `buildId`.

Modify the following sections.

- Prepare `jobId`
  - Please check `Solution 1`.
- Parse `buildId` from PR comments.
  - The `buildId` is always written in the PR comments. The set point is [getPrComment](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L137-L153).
  - Parse the body of the PR comment to obtain the buildId.
- Call [`GET /builds/{id}`](https://api.screwdriver.cd/v4/documentation#/v4/getV4BuildsId) to get `jobId`
- If the `jobId` obtained matches the job currently being executed, overwrite it; if not, make a new comment.

I prefer to develop with Solution 1.
The reason is that 2 requires more communication to the API to match the number of PR comments. This leads to load.

## Reference

PR Comment is created with the following source code flow

API([/PUT/builds](https://github.com/screwdriver-cd/screwdriver/blob/f44509d9f3bebeb5a5558ff60189aeb71b13c274/plugins/builds/update.js#L158-L269))  
-> [model.update()](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L527-L589)  
-> [model.updateCommitStatus()](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L286-L352)  
-> [scm.addPrComment()](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L1671-L1722)

**Comment by ibu1224** [comment]
I received a feedback within YJ.
I share solution 3, which is an improvement on solution 1.

## Solution 3. Add `jobName` to PR comments.
The difference from `Solution 1` is the use of `jobName` instead of `jobId`.
Users are happy to see `jobName`rather than `jobId`.

<details>
<summary>Modify the following, which is almost the same as `Solution 1.`</summary>

- Prepare `jobName`
  - Fortunately, `jobName` is readily available. It is resolved in [`updateCommitStatus`](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L286-L352), which calls [`addPrComment`](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L1671-L1722).
    - Add `jobName` to [`prConfig`](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L317-L323).
      - Now you can use `jobName` in `addPrComment`. 
- Parse the `jobName` in the PR comment.
  - We already have the ability to retrieve PR Comments from GitHub.[prComments](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L1677)
  - The body of the PR comments obtained is parsed to determine if the `jobName` matches.
    -  If the `jobName` matches, you can overwrite it, otherwise you can create a new one.
    - The function to [overwrite](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L376-L396) and the part to make [new comments](https://github.com/screwdriver-cd/scm-github/blob/d6aa24cfa5f71b29abbc9256b46100cca7ff51c6/index.js#L1700-L1710) have already been implemented.
- Write `jobName` in PR comments.
  - PR comments are formatted in [`getPrComment`](https://github.com/screwdriver-cd/models/blob/18b0bfaab3bdb15358f40a38ec668997d7c89973/lib/build.js#L137-L153) and sent to [`addPrComment`](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L1671-L1722).
    - Pass the `jobName` to getPrcomment and include the `jobName` in the comment.
 
</details>

**Comment by jithine** [comment]
I agree with solution 3 proposal 👍
