### ISSUE TITLE
Disabled jobs run in PR builds

### ISSUE THREAD

**Issue by yk634** [screwdriver-cd/screwdriver#2704]
**What happened**:
Even if I disable the job in Options, it still runs in the PR build.

- Options
<img width="954" alt="options" src="https://user-images.githubusercontent.com/59165943/167560659-7e1ecf46-b265-4463-b2aa-4ac44eb42246.png">

- PR build
<img width="1425" alt="pr" src="https://user-images.githubusercontent.com/59165943/167560697-86bba326-5476-4219-b681-6bc078702aea.png">

- Normal commit build is successfully disabled
<img width="1062" alt="builds" src="https://user-images.githubusercontent.com/59165943/167560925-845401bf-14e2-4de5-a24c-7be9a96546ce.png">

**What you expected to happen**:
I think disabled jobs should not be run even in PR builds.

**Comment by kumada626** [comment]
This issue might be relates to #1943.

**Comment by jithine** [comment]
We should not run PR builds for disabled jobs. @tkyi was looking into same issue from our internal users.

**Comment by itleigns** [comment]
Currently, disabled PR job runs when triggered by another job in chainPR or when run with Start/Restart pipeline form here.

**Comment by tkyi** [comment]
Should be fixed now with my changes
Seems like the UI is not reflecting the PR job state though

**Comment by itleigns** [comment]
There are two statuses for PR jobs: one in the form of `PR-X:jobname` and one in the form of `jobname`. The former is toggled by pressing the `Disable this job` button on the PR event workflowgraph and the latter is toggled on the commit event workflowgraph or option page.
I meant PR jobs run even if the state of the `jobname` format is `DISABLED`.
Currently, PR jobs run if and only if the both statuses are `ENABLED` when triggered by `Start` button or pull request.
On the other hand,  PR jobs run if and only if the statuses in the form of `PR-X:jobname` are `ENABLED` when triggered by another job or `Start/Restart pipeline form here`.

**Comment by jeffreytolar** [comment]
We were actually relying on this (the former) behavior; in some pipelines, we have dedicated jobs that are PR-only, and would do non-ideal things if run outside of a PR context. For those, we've had the parent job disabled, so that they couldn't be run accidentally.

Perhaps a job annotation could be used to separate the two use cases (like a "forbid manual starts" flag... although there'd need to be some way to distinguish PR vs non-PR builds), or the enabled state could be non-boolean (`{ENABLED,DISABLED}_{WITH_PR,WITHOUT_PR}`)?

**Comment by jeffreytolar** [comment]
Another use case for having PR builds still run if the parent build is disabled: we have some ~commit builds that are currently disabled since we don't want a new artifact produced yet (it'd pick up new library versions we aren't ready to roll out to that component); however, that blocks PR builds as well, making it harder to test that component with the new library version.

(Note: PR builds can still be started by creating an event with `"startFrom":"PR-123:jobname"` instead of using `"startFrom":"~pr","prNum":123`)

**Comment by jeffreytolar** [comment]
That last `Note` is likely #2728

**Comment by jeffreytolar** [comment]
Another potential fix that would help (although still have some friction): copy the enabled/disabled state from the parent jobs when creating the PR jobs, instead of checking on event creation; that way, the PR jobs could re-enabled independently of the parent.

**Comment by tkyi** [comment]
Wonder if this might be slightly related to https://github.com/screwdriver-cd/screwdriver/issues/2735
