### ISSUE TITLE
Disabled PR jobs can be re-run from the build details page

### ISSUE THREAD

**Issue by yk634** [screwdriver-cd/screwdriver#2728]
**What happened**:
As shown in the following image, the job can be re-run by pressing the Restart button on the build details page.
<img width="1406" alt="disable-prjob-restart" src="https://user-images.githubusercontent.com/59165943/177702925-49f60be1-9875-411d-a5aa-19183bdf3a8d.png">
If the same operation is performed on a normal event that is not a PR, the message "No jobs to start." is displayed and the job is not executed.

**What you expected to happen**:
Disable jobs are not executed even from the build details page.

**How to reproduce it**:
1. Disable the job executed in the PR event.
2. Select the job you have disabled and press "Go to build details".
3. Press "Restart" button.

**Comment by y-oksaku** [comment]
I agree with https://github.com/screwdriver-cd/models/pull/555#pullrequestreview-1047094026 that the restart button should not be able to be pressed.

Because if we click the restart button on a disabled job, then the PR event will appear the following image.

![restart_disabled_job](https://user-images.githubusercontent.com/43719835/180680452-097b370a-9fb1-419f-a133-d6e28a1735d6.png)
