### ISSUE TITLE
Dependency resolution issues

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#274]
We're experiencing odd issues with dependency resolution. `screwdriver-scm-base` and `screwdriver-data-schema` both use `Joi` to validate schemas. 

In one of our builds[1], it fails because of an error `Error: you must provide a joi schema`. This is thrown from [calling parseUrl](https://github.com/screwdriver-cd/scm-base/blob/master/index.js#L55) in `screwdriver-scm-base`. This is thrown because `Joi.reach` does a [validation check](https://github.com/hapijs/joi/blob/master/lib/index.js#L155) against the incoming schema. Specifically, it checks to see if the incoming parameter extends one of the `Joi` classes.

Because the schema passed into `parseUrl` comes from `screwdriver-data-schema`, it's considered a different class than the one packaged with the Joi module in `screwdriver-scm-base`. So when `Joi` evaluates whether the schema is a particular instance, it fails. 

[1] - https://cd.screwdriver.cd/pipelines/dcfd8d2b0d5ba460675a7d20b910ca298a846d17/build/dee12dc65d74c1c8924b537267241f63997162fa

**Comment by FenrirUnbound** [comment]
The most straight-forward solution I can think of is to have `screwdriver-data-schema` expose its `Joi` library directly.

**Comment by FenrirUnbound** [comment]
Another annoyance to add is that it's indeterministic: some `npm install` scenarios will result in each module having their own `Joi` module, and other `npm install` scenarios will result in a flatter dependency tree 😕

**Comment by FenrirUnbound** [comment]
Closing as un-reproducible

**Comment by d2lam** [comment]
Ugh I ran into this issue now:
https://cd.screwdriver.cd/pipelines/b1bdad711ff12c229a9fa6ed7831703dd74c3a93/build/167efbdc9eb3540fa91bacef04493ab0cc216643

**Comment by d2lam** [comment]
This might be coming from `retry-function` since it's using v6 joi and that doesn't support `Joi.reach`.

**Comment by d2lam** [comment]
Yuppp that was it. Build passed now: 
https://github.com/screwdriver-cd/scm-bitbucket/pull/5

**Comment by adong** [comment]
I'm having the same issue, if I develop `screwdriver-data-schema` locally.

Like in `package.json`.

```
  "dependencies": {
    "screwdriver-data-schema": "file:../data-schema",
```

This will cause errors.

**Comment by adong** [comment]
Haha, I got it resolved. FYI: @FenrirUnbound @d2lam @jithin1987

The idea is that because we are developing locally, so we have `node_modules/` in the `data-schema` directory as well. Obviously, that's not the library used in `screwdriver/` repo, since they are referencing different place of packages.

I tried `npm link` and `npm install` from file WILL NOT work, because it will install `node_modules/` inside `data-schema` directory, and cause divergence.  

Then I tried `npm pack` and install from tarball, like `npm install /Users/adong/github/sd/data-schema/screwdriver-data-schema-18.0.0.tgz`

Works fine, finally. Intuitively, it makes sense, because the tar doesn't contain `node_modules`, the caveat part is that, we have to pack for every code changes manually. 😕 

Reference: https://medium.com/@the1mills/how-to-test-your-npm-module-without-publishing-it-every-5-minutes-1c4cb4b369be

**Comment by adong** [comment]
Add some instructions

```
rm package-lock.json
rm -rf node_modules/screwdriver-config-parser
rm -rf node_modules/screwdriver-data-schema

npm install /Users/adong/github/sd/data-schema/screwdriver-data-schema-18.0.0.tgz
npm install /Users/adong/github/sd/config-parser-local-files/screwdriver-config-parser-3.1.0.tgz
```
