### ISSUE TITLE
[Feature Request] Different bookends can be executed on different build clusters.

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#2763]
**What happened**:

I want to create build clusters with different bookends and execute different bookend on each one.

For example, execute different setup bookends when the build clusters uses different runtimes such as `containerd` and `Docker`.

**What you expected to happen**:

Different bookends can be executed on different build clusters.

**How to reproduce it**:

---

I'm glad if you can give me a response if you have any opinions :pray:

**Comment by yk634** [comment]
# Proposal
I have thought of a way to implement a feature that allows bookends to be switched for each build cluster.

## How to set up by cluster administrator
Allows configuration in `config/local.yaml`.    
https://github.com/screwdriver-cd/screwdriver/blob/a9427d7f4e487eaacea2a8775c88c125b9f82e0e/config/default.yaml#L279-L286

Change the structure so that the current setting of `bookends.setup(teardown)` can be set to `bookends.<cluster_name>.setup(teardown)`.  
Prepare a `default` in case the cluster is assigned to a cluster not listed here.  

Example:
```
bookends:
  default:
    setup:
      - scm
      - screwdriver-cache-bookend
    teardown:
      - screwdriver-artifact-bookend
      - screwdriver-cache-bookend
  clusterA:
    setup: ...
    teardown: ...
  clusterB:
    setup: ...
    teardown: ...
```

The way environment variables are set also needs to be changed.    
https://github.com/screwdriver-cd/screwdriver/blob/a9427d7f4e487eaacea2a8775c88c125b9f82e0e/config/custom-environment-variables.yaml#L352-L360

Set `BOOKENDS_SETUP(TEARDOWN)` to `BOOKENDS` to set the json containing the cluster name.

Example:
```
BOOKENDS: '{"default": {"setup": ["scm", ...], "teardown": [...]}, "clusterA": {"setup": ["scm", ...], "teardown": [...]}}'
```

## Program Modifications

### API config
Change the structure of the config file to correspond to the above configuration method.    
In particular, the `custom-environment-variables.yaml` needs to accommodate the change in json structure.  
https://github.com/screwdriver-cd/screwdriver/blob/a9427d7f4e487eaacea2a8775c88c125b9f82e0e/config/custom-environment-variables.yaml#L352-L360

### API bin/server
In line with the change in the bookends structure of `config`, when instantiating a `Bookend`, it is passed as an argument as `bookends`.  
https://github.com/screwdriver-cd/screwdriver/blob/a9427d7f4e487eaacea2a8775c88c125b9f82e0e/bin/server#L112-L121

### build-bookend
Allows `initializeBookend` to be executed without separating it into `setup` and `teardown`.  
https://github.com/screwdriver-cd/build-bookend/blob/075b254f55bc67d1fd897762d45f31a0af639f15/index.js#L106-L110

`getSetupCommands` and `getTeardownCommands` take the cluster name as an argument and retrieve the setup and teardown lists from `this.bookends`, respectively.  
If there is no cluster name such as `multiBuildCluster: false` or if the cluster is not specified in bookends, it is obtained from `bookends.default`.  
https://github.com/screwdriver-cd/build-bookend/blob/075b254f55bc67d1fd897762d45f31a0af639f15/index.js#L112-L151

### buildFactory
When executing `getSetupCommands` and `getTeardownCommands`, pass `buildClusterName` as an argument.  
https://github.com/screwdriver-cd/models/blob/86aeae16a778c96b056c4d1d818b81cac1ca704a/lib/buildFactory.js#L253-L256

**Comment by tkyi** [comment]
Will bring it up with the team.

Small note: Can we make sure we bump major with this change?

**Comment by jithine** [comment]
Proposal looks good to me. 👍

**Comment by yk634** [comment]
> Small note: Can we make sure we bump major with this change?

Because of the change in the way `config/local.yaml` is set up, it will no longer be possible to set it up in the same way as before.
Therefore, it is a good idea to bump major with this change.
