### ISSUE TITLE
UI Flashes the entire screen sometimes while jobs are running

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#298]
Steps to reproduce:
- Click start on a job
- The ui flashes the whole screen while it is starting

I have also seen the entire screen flashing every second or so, but I'm not sure how to reproduce. In this example there were no logs coming in at all, so it was just showing a spinner and flashing the screen.

**Comment by petey** [comment]
This may be an artifact of how we are updating the build model. When a build is `QUEUED` we check periodically to see if the build status has changed by making calls to reload the model. When the model changes, this will cause a UI refresh. This technically should only cause components with updated data to redraw, but since we only pass the model around and not specific data, it may be more aggressive then we'd like.
You should see similar behavior when a step completes on a `RUNNING` build, as that would trigger another load against the build model.

**Comment by stjohnjohnson** [comment]
No longer happening (at least that I've been unable to reproduce now).
