### ISSUE TITLE
Ability to Restart Pipeline for PR build when Path exists

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3011]
**What happened**:
In the case of `screwdriver.cd/chainPR: true`, missing an ability to do "Restart pipeline from here" when a job has a path that is leading to it from the `~pr` trigger. Please see the image below and [the pipeline](https://cd.screwdriver.cd/pipelines/12980/pulls) where issue was observed. In the case of this event, there is a join condition that needs to be satisfied before `random-job` is triggered. 

<img width="1899" alt="Screenshot 2024-01-30 at 1 23 33 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/a7e7a2d9-0961-4a69-ae87-265fbfe217bb">

**What you expected to happen**:

Our internal user reported that the functionality to do "Restart pipeline from here" for the `random-job` existed before and it is no longer available now. If this is a regression case due to a recent change, we should bring this ability back. 

**How to reproduce it**:
Check [the pipeline](https://cd.screwdriver.cd/pipelines/12980/pulls) and create a new event with the `Start` button to reproduce.
 
<img width="1711" alt="Screenshot 2024-01-30 at 1 44 56 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/a240a01e-e2aa-4413-a123-c1ce8a8169e6">

**Comment by jithine** [comment]
@kumada626 I guess the approach we did for https://github.com/screwdriver-cd/screwdriver/issues/2038 is not working for join scenarios. We used to get a join build, but what is not happening any more, which is impacting the restart functionality. 

We suspect https://github.com/screwdriver-cd/screwdriver/pull/2974/files might have to do something here, but would need more investigation

**Comment by kumada626** [comment]
@jithine I think this problem is caused by the chainPR scenario, not the join scenario.
In PRs https://github.com/screwdriver-cd/ui/pull/701 and https://github.com/screwdriver-cd/ui/pull/706, we hide restart button on a job that has not triggered in the PR related event.
In the pipeline presented, the random-join job has an additional join condition for second-job and start-commit job by PR. However, since start-commit job is a commit-triggered job, it will not be triggered by PR. Therefore, the random-join job is never triggered when triggered by PR.
I think the solution to this problem would be to change the specification to allow a restart if the path exists, even if it is never triggered by the PR.
In that case, PRchain builds that have not been triggered because the previous build failed would still be able to be manually started, but if that is not a problem, I think it would be better to fix it that way.

**Comment by jithine** [comment]
@kumada626 Thanks for you analysis. I agree with your solution to check for path. 
How ever we where just curious on why this behavior changed suddenly and where did that join build go ? As per our customer this was working fine until recently.

**Comment by jithine** [comment]
Since the root cause seems to be a missing join build, wondering if this PR https://github.com/screwdriver-cd/screwdriver/pull/2974 was for the same in a non-pull request context

**Comment by kumada626** [comment]
I think that the missing of that join build was the correct state. Due to the PR, the second-job is executed, resulting in the creation of the random-job in a CREATED state. However, in the presented workflow, the start-commit job is never executed for a PR, so the join condition for the random-job would never be met in the context of a PR event. As the join condition is never fulfilled, the random-job should not be triggered automatically by the PR. Since it is not executed, I don't think it should be restarted. Therefore, if it was working before, I think that it might have been an unexpected behavior that deviated from the definition.

As a new specification, the key point is whether we should allow manual execution of the builds displayed in the workflow graph, even though they are not automatically triggered by a PR.
