### ISSUE TITLE
Sequelize datastore is broken with MySQL

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#325]
Sequelize is generating a blob for a primary key when using MySQL, which breaks in a way similar to this: http://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length

**Comment by stjohnjohnson** [comment]
Do you have the exact message?  Which table?  What operation was happening at the time?

**Comment by catto** [comment]
There are two issues when I try to run with MySQL. I used stable Screwdriver containers and run  docker-compose.yml generated by in-a-box.py with mysql configurations.

### 1. Wrong mysql module is installed
When I specify mysql dialect in the config, the api container shows this error:
```
api_1    | > screwdriver-api@3.1.40 start /usr/src/app/node_modules/screwdriver-api
api_1    | > ./bin/server
api_1    |
api_1    | /usr/src/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:24
api_1    |       throw new Error('Please install mysql package manually');
api_1    |       ^
api_1    |
api_1    | Error: Please install mysql package manually
api_1    |     at new ConnectionManager (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:24:13)
api_1    |     at new MysqlDialect (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/index.js:12:28)
api_1    |     at new Sequelize (/usr/src/app/node_modules/sequelize/lib/sequelize.js:233:18)
api_1    |     at Squeakquel (/usr/src/app/node_modules/screwdriver-datastore-sequelize/index.js:118:23)
api_1    |     at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-api/bin/server:28:19)
(snip)
```
I guess `screwdriver-datastore-sequelize` requires `mysql2` module but `sequelize` module in the screwdriver image requires `mysql` module. It can be fixed by installing mysql module.

Inside the container:
```
    if (sequelize.config.dialectModulePath) {
      this.lib = require(sequelize.config.dialectModulePath);
    } else {
      this.lib = require('mysql');
    }
```

Latest `sequelize` (v4) uses `mysql2`and it's currently unstable.
https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/connection-manager.js#L30-L34


### 2. MySQL does not allow adding index to TEXT/BLOB column with no length

Though I installed correct mysql module into the container, I got this error:
```
api_1    | error:  SequelizeDatabaseError: ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'id' used in key specification without a key length
api_1    |     at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
api_1    |     at Query._callback (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
api_1    |     at Query.Sequence.end (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
api_1    |     at Query.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
(snip)
```
`sequelize` tries to create the new table with given definitions, and it generates the schema which includes BLOB column for primary key with no length option.
I'm trying to fix this issue by modifying `screwdriver-datastore-sequelize`, but it seems that `sequelize` module needs to be fixed.

**Comment by stjohnjohnson** [comment]
1.  Ahh, my bad I was following latest docs: http://docs.sequelizejs.com/en/latest/docs/getting-started/  Should be easy fix to https://github.com/screwdriver-cd/datastore-sequelize/blob/master/package.json#L44

2. We could probably fix that here: https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L87 Instead of using TEXT, we can use STRING with appropriate size (determined from `joi.describe()`).

Example:
```javascript
> joi.string().length(15).describe()
{ type: 'string',
  invalids: [ '' ],
  rules: [ { name: 'length', arg: 15 } ] }

> joi.string().max(15).describe()
{ type: 'string',
  invalids: [ '' ],
  rules: [ { name: 'max', arg: 15 } ] }
```

**Comment by catto** [comment]
@stjohnjohnson Oh I missed STRING which accepts length arg... I just looked around TEXT and BLOB from error messages. Thank you I will fix them tomorrow!

**Comment by d2lam** [comment]
@catto  Your PRs were merged. Let us know if you're still having problems.

**Comment by catto** [comment]
@d2lam I confirmed that the latest screwdriver works with MySQL. Thanks for reviewing!

**Comment by d2lam** [comment]
@catto  Yay!!!
