### ISSUE TITLE
PR builds created by non-user do not run

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#335]
PR builds are not being created if the user that creates the PR is not in our database:

It is checking if user exists here: https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/index.js#L187-L193

And user is from `parsed.username`, which is `pull_request.user.login` from the payload: https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L448

```
{
  "action": "reopened",
  "number": 327,
  "pull_request": {
    "url": "https://api.github.com/repos/screwdriver-cd/screwdriver/pulls/327",
    "id": 91439458,
    "html_url": "https://github.com/screwdriver-cd/screwdriver/pull/327",
    "diff_url": "https://github.com/screwdriver-cd/screwdriver/pull/327.diff",
    "patch_url": "https://github.com/screwdriver-cd/screwdriver/pull/327.patch",
    "issue_url": "https://api.github.com/repos/screwdriver-cd/screwdriver/issues/327",
    "number": 327,
    "state": "open",
    "locked": false,
    "title": "Update github to version 6.0.1 🚀",
    "user": {
      "login": "greenkeeperio-bot",
```

**Comment by d2lam** [comment]
```
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'unsealToken' of null"}
```

**Comment by petey** [comment]
The call to `getRepoInfo` doesn't actually need any authentication. I'll make a change to scm-github to make the auth call optional, and the PR handler can do away with loading the user entirely.

**Comment by FenrirUnbound** [comment]
@petey The authentication is needed because of request thresholds. Github tracks usages based on IP and token, where the request limits with a token are significantly higher than IP-based. If there are too many requests from the IP that our cluster is associated with, then we will be blocked from accessing even public information on the API.

`scm-github` could be made to have it optional, but that's why we would prefer to have the token. I opened up #336 to help address this issue in a more graceful way than we are handling it now
