### ISSUE TITLE
Git-flow functional test timed out

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#358]
Failed at different scenarios each time. Some examples:

```
1) Scenario: Updated Pull Request - features/git-flow.feature:24
   Step: Then any existing builds should be stopped - features/git-flow.feature:27
   Step Definition: features/step_definitions/git-flow.js:176
   Message:
     function timed out after 60000 milliseconds

2) Scenario: Closed Pull Request - features/git-flow.feature:30
   Step: When the pull request is closed - features/git-flow.feature:32
   Step Definition: features/step_definitions/git-flow.js:101
   Message:
     function timed out after 60000 milliseconds
```

**Comment by minz1027** [comment]
## Mediation and Results

1. Action: Add more nodes in aws
Results: The tests passed immediately. The func tests went pretty stable in the first few days after the mediation, but went back to the old flaky way later on.

2. Action: Increase git-flow timeout
Results: The tests below still failed occasionally. Sometimes restarting the build may fix it.
```
1) Scenario: Updated Pull Request - features/git-flow.feature:24
   Step: Then any existing builds should be stopped - features/git-flow.feature:27
   Step Definition: features/step_definitions/git-flow.js:176
   Message:
     function timed out after 60000 milliseconds

2) Scenario: Closed Pull Request - features/git-flow.feature:30
   Step: When the pull request is closed - features/git-flow.feature:32
   Step Definition: features/step_definitions/git-flow.js:101
   Message:
     function timed out after 60000 milliseconds
```

Unlike other tests, for git-flow, it is possible that `multiple builds` are queueing or running at the same time.

When testing today, we saw that most of the builds are queueing for quite a long time and only 1 or 2 got running at the same time. That's why the tests timeout. 

3. Action: Rotate nodes in aws (which will clean up the disk space)
Results: Tests got passed and were pretty stable.

**Possible reason for the flaky tests**: running multiple concurrent builds when disk space is low?

**Comment by tkyi** [comment]
**UPDATE:**

Bumped timeout up to 240000 milliseconds 1/4/17 (https://github.com/screwdriver-cd/screwdriver/pull/411). And upgraded nodes to `m3.large`. Don't seem to have seen the timeout issue since then.
