### ISSUE TITLE
Search results page Epic

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#394]
- [x] Show number of results
- [ ] Show term used to search, or highlight search term in results
- [ ] Search filters

**Comment by d2lam** [comment]
@petey: Can you be more specific about `search filters`? What do we want to filter on? In wercker, we could filter by owner: "Me" or the org that I belong to, aka "Screwdriver", but we don't have this capability yet. I would imagine **sorting** to be more appropriate in our case.

**Comment by petey** [comment]
If you take a look at what the UI is actually doing, you'll see that all the filtering that is done right now is handled entirely in the UI after downloading the list of all pipelines in the system. There would be nothing stopping you from making that somewhat more intelligent, so that one could search for `owner:screwdriver-cd`, `repo:ui`, or `branch:patch1`. The results should already be sorted alphabetically.

I called this issue an "epic" as a sort of expected the bullets to be pulled out individually as separate issues/ pull-requests. I think we'd get the best bang for the buck to handle the first two bullets and leave the last for when we switch to a relational datastore.

**Comment by d2lam** [comment]
@petey  Thanks, Petey. We worked on the first 2 items. Let's discuss the last one later.
