### ISSUE TITLE
Pipeline ID would be reused when using MySQL

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#535]
### Abstract
We can choose MySQL as a main datastore for Screwdriver. It uses auto_increment to generate pipeline ID, but it doesn't persist auto_increment value. This behavior causes an issue that pipeline ID would be reused.

### How to reproduce
Choose MySQL as a database and set InnoDB as a storage driver (default setting).

* Given these 6 pipelines:  
1, 2, 3, 4, 5, 6
* And an admin of pipeline 2 and 6 removes their pipeline:  
1, 3, 4, 5
* When MySQL restarts (accident or scheduled)
* And someone creates a new pipeline.
* Then the pipeline will be assigned 6 as ID, not 7:
1, 3, 4, 5, 6

### What is the problem
Some users would write a URL of a pipeline to their README or somewhere, or set notifications to slack channel. 
It shows other pipeline than previous one when someone opens the URL after removing the pipeline, restarting MySQL and creating a new pipeline by another person. It's a bit confusing to users. I think the desired behavior is a 404 page.

This issue doesn't occur when a user doesn't choose MySQL as a database. The behavior is by design of MySQL actually. It wouldn't be a problem for most situation, but I think it would be a problem in this case.

**Comment by FenrirUnbound** [comment]
After reading the documentation, it looks like this is the expected behavior of MySQL. [Reference](https://dev.mysql.com/doc/refman/5.5/en/innodb-auto-increment-handling.html). 

* > To initialize an auto-increment counter after a server restart, `InnoDB` executes the equivalent of the following statement on the first insert into a table containing an AUTO_INCREMENT column.

* > `InnoDB` uses the in-memory auto-increment counter as long as the server runs. When the server is stopped and restarted, InnoDB reinitializes the counter for each table for the first INSERT to the table, as described earlier.
A server restart also cancels the effect of the AUTO_INCREMENT = N table option in CREATE TABLE and ALTER TABLE statements, which you can use with InnoDB tables to set the initial counter value or alter the current counter value.

**Comment by FenrirUnbound** [comment]
A straightforward solution would be to have another table that tracks the latest IDs. This would be more resilient to in-memory counters being lost on a server restart, but I currently don't know what it would be like to implement it across all SQL variants.

Going forward, we would have to come up with a more resilient schema to avoid a scenario like this.

**Comment by jithin1987** [comment]
Please re-open if this is still an issue.
