### ISSUE TITLE
Build Timeout

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#545]
As a screwdriver user,
I want my builds to timeout after some period of time,
So I'm not eating up system resources forever if something goes wrong.

We should add some configuration to allow jobs to be forcefully terminated as a failure if they go over established time limits

First Pass:
- [x] Jobs will be killed by the executor after 90 minutes of run time.
- [x] Jobs can be configured by users with a timeout of up to a maximum of (X) minutes, with a system default of 90 minutes if not defined.
- [ ] Validate annotation - Max: 10hrs (Builds should run fine if user timeout is less than the max)
- [ ] Default timeout from the cluster admin side

**Comment by minz1027** [comment]
### Updates 02/26
https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L64
https://github.com/taskrabbit/node-resque/tree/v4

Since we have queue now, we can actually leverage on `resque`'s `enqueuIn` function, which enqueues the job in a future time from now. Whenever we enqueue a build `start` job, we can also enqueue a `stop` job for that build and delay it's execution to be 90 mins later.

User can override the default timeout in their job annotations. We can check on that and set the delay time properly.

**Comment by FenrirUnbound** [comment]
A point was brought up that we should also be wary of setup and teardown steps timing out. On one hand, if a teardown step does not exit correctly, the build could left in a hanging state. An opposing concern that came up was: by managing all steps under a single timeout, we lose out on the opportunity to debug a build if it times out before executing the artifact upload procedure.

Should we consider separate timeouts for everything (e.g., timeout for setup, timeout for user-defined steps, timeout for teardown)?

**Comment by jithin1987** [comment]
I believe timeout for setup and user defined steps should be same, no need to make it complicated for our implementation.

One one hand if user defined steps are failing then there might be value in having artifacts saved, but it might really be a bad test or deployment which is stuck causing the step to get aborted, then there won't be any legit artifacts to be saved.

So we can either just do one timeout overall or do a grace period of 10 - 15mins to finish uploading artifacts.

**Comment by FenrirUnbound** [comment]
> I believe timeout for setup and user defined steps should be same, no need to make it complicated for our implementation.
>
> One one hand if user defined steps are failing then there might be value in having artifacts saved, but it might really be a bad test or deployment which is stuck causing the step to get aborted, then there won't be any legit artifacts to be saved.
>
> So we can either just do one timeout overall or do a grace period of 10 - 15mins to finish uploading artifacts.

I agree that the setup and teardown steps should also have a timeout ceiling so that misbehaving bookends don't eat up resources either. 

My question would be more along the implementation: do we want the setup/teardown steps to have a separate timeout or just pick an arbitrary amount and revisit it when the need for it arises?

**Comment by minz1027** [comment]
### Thoughts about implementation
To continue the discussion in this PR: https://github.com/screwdriver-cd/launcher/pull/160

From the PR, seems like we are setting timeout value as an `ENV` or flag to `launch` binary. If we implement it that way, then we need to modify ALL executors plugins to take in the field and pass it to launcher, e.g. for executor-k8s: https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.tim, for executor-docker: https://github.com/screwdriver-cd/executor-docker/blob/master/index.js#L206

@FenrirUnbound How do we currently pass in all the variables to the launcher (e.g., build ID, emitter path, etc)? 
^^^ in all executors as I mentioned

Instead of touching all executors' code, can we save this as a field in the job model and fetch it from launcher? we are fetching the job in launcher already. That way we only need to touch launcher.

Or can you @FenrirUnbound share more details on how you're going to handle the flow if there's anything I misunderstand? The flow to pass the value from users' config to launcher.

**Comment by FenrirUnbound** [comment]
> How do we currently pass in all the variables to the launcher (e.g., build ID, emitter path, etc)?
^^^ in all executors as I mentioned

Performing the look-up on the launcher is unnecessary. It may me the most agnostic approach, but all the needed information is available at the executor level.

> Instead of touching all executors' code, can we save this as a field in the job model and fetch it from launcher?

That's just shifting the work around. You're asking to, instead of changing it at an interface level, to change it at an implementation level. Yes, you avoid touching the executors, but now you're meddling with the `data-schema` and the `models` and the `screwdriver` API. And our experience with CI/CD tooling is that implementation specific workflows are not simple to maintain in the long run.

**Comment by minz1027** [comment]
But where do you store `timeout` specified by user in the yaml? It has to be stored somewhere in the job right? most likely the `permutation` field in the job. You don't need to change `models` and screwdriver `API`, that `timeout` is inside permutation and will be saved to datastore when we create the job.

**Comment by FenrirUnbound** [comment]
> But where do you store timeout specified by user in the yaml

In the end state, we don't want the user's configuration to be the only source of this value.

**Comment by d2lam** [comment]
**4/16/18**

Added PRs for cluster admins to configure build timeout.

**Comment by d2lam** [comment]
This feature is done
