### ISSUE TITLE
Calling create and then update on a token/secret seals the value twice

### ISSUE THREAD

**Issue by ian-fox** [screwdriver-cd/screwdriver#554]
Currently if you `create` a token/secret, or call `update` on one the value is sealed by iron.

If the model continues to be used after that and has `update` called on it again, iron will seal the (already sealed) value again.

**Comment by stjohnjohnson** [comment]
@ian-fox did you have an example of this happening?

**Comment by d2lam** [comment]
I vaguely remember this. But from what I remember, if this happens, then it will happen if we intentionally do this inside the model. It doesn't happen as long as we don't call `update` immediately after `create`, which we don't since there is no reason to. I don't think any endpoint would `update` immediately after `create`. It does it in 2 separate calls. I will close this issue. Please feel free to reopen if you find some specific example where this is a bug.

**Comment by ian-fox** [comment]
Oh whoops sorry @stjohnjohnson! I missed your notification among all the other screwdriver ones. I've turned down my notification settings so hopefully that doesn't happen again.

I think Dao's assessment is correct.
