### ISSUE TITLE
UI shows wrong order of build bubbles

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#555]
In certain cases, the order of build bubbles is wrong. Haven't been able to figure out how to reproduce this. Seems to happen to random pipelines.

Example:
<img width="557" alt="screen shot 2017-05-16 at 11 01 58 am" src="https://cloud.githubusercontent.com/assets/3401924/26121271/8ee74954-3a28-11e7-9083-e2b40fa5a9b5.png">

**Comment by petey** [comment]
When I've seen this, it appeared that the build bubbles were labeled with the correct job names, but the builds that were being associated with each bubble was incorrect. The bubble highlight is done through the build ids, so when the wrong builds are associated with a given job, the highlights jump around incorrectly.

I'd need an example project that exhibits this behavior (that isn't being regularly changed) for further investigation.

**Comment by petey** [comment]
The UI is making an assumption that all data that comes from the api is sorted properly. The API should be sorting things by `createTime`. It turns out that in many cases the `createTime` is not a valid value when compared to the model id. There are instances where the `createTime` for a build happens after the `endTime` of the same build.

I will add some logic on the UI to properly sort models based on model ids.

**Comment by d2lam** [comment]
@petey figured out that UI is doing the correct thing. The API is not returning the list of event's builds in the correct order. Closing this issue now.
