### ISSUE TITLE
Skipping builds

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#587]
Some users would want to avoid builds even if some commits were pushed to a repository associated with the pipeline. For instance, I want to avoid new build when I fix only a document.
It would be great if there is a feature which can skip a specific build.

I think CI tool users accustomed to include `[skip ci]` in a commit log when they want to skip their build.
https://circleci.com/docs/1.0/skip-a-build/
https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by stjohnjohnson** [comment]
I like that option.  Do we want it to work also in Pull Requests or just on merges?

**Comment by petey** [comment]
I've always thought it was confusing that it worked in one situation and not the other.

**Comment by d2lam** [comment]
I feel like we should make it simple by allowing it in both. Users should know the negative effects of `[skip ci]` and use it at their own risk.

**Comment by d2lam** [comment]
This is working 👍

**Comment by tkyi** [comment]
Need to add this feature to documentation still

**Comment by tkyi** [comment]
Since `opened` pull request webhooks from Github do not contain a commit message, pull request builds are not skipped (https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L672-L683).

I think it's okay to leave the functionality this way with [clear documentation](https://github.com/screwdriver-cd/guide/pull/110). If this lack of pull request support becomes a feature request in the future, a new issue can be created.
