### ISSUE TITLE
Log Service uses TCP-based communication

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#598]
## Context

Currently, the [`launcher`](https://github.com/screwdriver-cd/launcher) communicates with the [`logservice`](https://github.com/screwdriver-cd/log-service) through Unix socket.

In order to support VM builds in Kubernetes, we can no longer use a Unix socket as a way for these two components to communicate with each other. Although the title of this issue suggests TCP-based communication, the implementation can really be anything as long as it's not the current Unix socket methodology.

## Implementation

TBD

## Outcome

* Launcher<-->LogService communication no longer uses Unix-socket

## References

* Related issue: #597

**Comment by stjohnjohnson** [comment]
Just curious, why can't we use unix socket for communicating? @jer 

Currently, we run both the log service and the launcher inside the same docker image, is there a reason we can't access a shared unix socket during that time?

**Comment by jer** [comment]
Well we were initially thinking that they were separate containers, which is the real issue. I guess they are combined in the same container at this point:

https://github.com/screwdriver-cd/executor-k8s/blob/3def5dcc516c41d7b3a345676b7ddf6976e925dd/config/pod.yaml.tim#L41

So the problem here just becomes use of the /opt/sd volume mount. Basically the core of the issue is that Hyperd can only share directories from the base host into containers, which cannot work with unix sockets. If the unix socket was created outside of the volume mount, it should work fine.

**Comment by jithin1987** [comment]
No longer an issue.
