### ISSUE TITLE
BUG: Running the server locally fails because of queue config

### ISSUE THREAD

**Issue by joelseq** [screwdriver-cd/screwdriver#718]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Screwdriver.cd version**: 0.5.29

**Environment**:
- **Cloud provider or hardware configuration**: localhost
- **OS** (e.g. from /etc/os-release):macOS

**What happened**: Server crashed when I tried to run locally using `npm start`:

![screenshot](https://user-images.githubusercontent.com/12389411/29639181-b844e8d6-880e-11e7-8396-9c3c848a6f33.png)

**What you expected to happen**: I expected the server to start up.

**How to reproduce it** (as minimally and precisely as possible): Run `npm start`

**Anything else we need to know**: This is being caused by [these lines of code](https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L131-L138). Commenting out the `queue` section from `default.yaml` fixes the issue.

**Comment by tkyi** [comment]
Closing issue because it is solved by Petey's fix.

You just need to set default to string false (`"false"`) in your `default.yaml` (https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L132) or set environment variable `EXECUTOR_QUEUE_ENABLED ` to `false` in your `local.yaml` (https://github.com/screwdriver-cd/screwdriver/blob/master/config/custom-environment-variables.yaml#L133).
