### ISSUE TITLE
Build job on successful completion of an external pipeline's job

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#770]
## Context

Phase 1 for https://github.com/screwdriver-cd/screwdriver/issues/768

Given an external pipeline P and a job in P named `P_JOB`, a job `X `should be able to rebuild itself after successful completion of `P_JOB`

Eg:  `X: requires: ["~sd@P:P_JOB"]`

**Comment by d2lam** [comment]
For implementation, we think of making a new table called `triggers`. This would include: pipeline, jobname, trigger. 

Example: for pipeline 5678
```
jobs: 
   test:
      requires: ~sd@1234:main
```

The table will be:

| pipelineId   |      jobName      | trigger |
|----------|:-------------:|------:|
| 1234 |  main | 5678:test |
| 1234 |  main | 5555:component |

We need this table because the config is defined inside pipeline 5678, but we need to do the triggering when pipeline 1234@main completes. 

We decide to make a separate entry for each trigger (instead of an array of triggers) because it will be easier to maintain. For example, when `5678:test` job no longer has the `requires`, we can query based on `triggers`, and delete it. 

We split the story into multiple tasks:
- [ ] Design doc: reflects new design (remove rebuild_on, etc.)
- [ ] Data-schema for triggers table
- [ ] Allow `~sd@pipelineId:jobName` for `requires`
- [ ] Models add/remove entry from table
- [ ] PUT /builds triggers jobs that require it.

**Comment by jithin1987** [comment]
@d2lam 

> We need this table because the config is defined inside pipeline 5678, but we need to do the triggering when pipeline 1234@main completes.

How does triggers be updated and or cleaned up in this table ?
Eg: Lets say 5678:test modifies it's requires syntax from `~sd@1234:main` to `~sd@2234:main, we need a way to update/remove old entry

**Comment by d2lam** [comment]
@jithin1987  Yes, so that should be taken care by `Models add/remove entry from trigger table`. Probably inside pipeline sync, it should do a query to look up `trigger == 5678:test`, and make sure that the values associated with it are correct. (remove/add entry if necessary)

**Comment by petey** [comment]
@jithin1987 The triggers config should behave similar to how we treat jobs in pipeline sync. We can compare the current (db) config to the expected (new) config, and make changes as required.

**Comment by tkyi** [comment]
*Update*: If two jobs in the same pipeline are triggered by the same external trigger, only one event should be triggered.

**Comment by jithin1987** [comment]
>Update: If two jobs in the same pipeline are triggered by the same external trigger, only one event should be triggered.

Yep, I've called this case out in Objective 2 at https://github.com/screwdriver-cd/screwdriver/issues/768

**Comment by tkyi** [comment]
Blog post: http://blog.screwdriver.cd/post/167490548294/new-workflow-features-in-screwdriver
Documentation: https://docs.screwdriver.cd/user-guide/configuration/workflow#remote-triggers
