### ISSUE TITLE
GitHub Issue Labels

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#83]
Right now I set up some basic ones for priority and impact, but there are a lot of other examples/best practices out in the wild.  What do you think we should do?

Links:
 - https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/
 - https://www.quora.com/What-is-the-best-way-to-name-GitHub-issue-labels
 - https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63#.702vtaqe6

**Comment by tkyi** [comment]
I have a rough idea of what labels we could use:
https://github.com/tkyi/cucumber-junit/labels

The basic principles are:
- the crazier/more intense a color, the more urgent the issue
- any labels that are equal in weight are equal in color
- things like priority or status have different colors according to their status/urgency
 
Another idea I had was that we could use something like `review/withReporter` and `review/withTeam` like how things are done in Jira. That way people who create Pull Requests can see easily if someone has reviewed their PR and left a comment for them to fix. Likewise, reviewers can see that comments have been addressed and re-review PRs. Or we could just merge the two into one flag; either way.

Note: The `status` labels are more for Issues.

**Comment by FenrirUnbound** [comment]
I really like the approach to colors. A couple of questions that come to mind:

1. It may be me, but `change/minor` and `change/patch` are the same color. Was that intentional? My impression was that the major change was big, so it's a more pronounced color, while the minor & patch tags were backwards compatible and so it doesn't need to be called out as loudly.

2. There are tags for platforms. Do you really mean templates instead?

3. Less functional, more of an observation (like the sky is blue): the color for `platforms` is very, very similar to `type`.

**Comment by tkyi** [comment]
@FenrirUnbound 
1. Yes, it was intentional, but I'm open to any suggestions if you take issue with that or think it might be more clear if the two minor/patch changes are different colors.

2. Platform, template, language; which one makes the most sense to you?

3. Yeah I can change the colors. I think I just wanted to avoid using yellow, red, or green since they are more reserved for things such as `status` or `priority`. Any hexadecimal color should work, so very open to any suggestions!

**Comment by stjohnjohnson** [comment]
Love it!

2. We shouldn't be debugging people's platform/template/language.  So I might remove/repurpose that.

**Comment by tkyi** [comment]
@stjohnjohnson 

1. Honestly it was more of a "this PR is in this language" sort of label. But I will remove it!

If everyone is okay with it, I'm going to start removing the default labels and adding the new ones to our existing repos. (And hopefully finding a way to automate it in the generator for new repos..)

**Comment by petey** [comment]
👍
