### ISSUE TITLE
Allow public access to build page and artifacts

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#870]
## Context

https://github.com/screwdriver-cd/screwdriver/issues/858 introduced authentication for accessing store data. While this is important in enterprise applications this is not desirable in public instances of SD. 

## Objective

1. Allow SD cluster admin to configure public access to build page and artifacts.

**Comment by stjohnjohnson** [comment]
# 3/16

Guest mode is now available.  There are still two bugs:
 - When not logged in, everything shows as blank pages (due to 403 errors), **need UI redirects.**
 - When logged in as guest and trying to perform write operations, user is presented with a strange error message "Missing scope".  **Need better UI message.**

**Comment by jithin1987** [comment]
> When not logged in, everything shows as blank pages (due to 403 errors), need UI redirects.

Will be fixing this on a priority.

**Comment by tkyi** [comment]
These changes are working in prod 👍
