### ISSUE TITLE
Build Page Redesign

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#871]
Spinning off a story from #423 to address a redesign of the build page to more closely match the design of other pages in the app, and to improve the overall UX for the page.

### Mocks
![main mock](https://user-images.githubusercontent.com/78533/35757212-fb766096-0822-11e8-8c05-7de9d4c74f93.png)
* [x] New build page header
* [x] Sidebar for steps (scrollable)
   * [x] Collapsable/Grouped bookends
* [x] Scrollable logs
* [x] Artifacts tree
* [x] Selecting a step displays logs for that step
* [x] Running steps should auto-open logs unless the user is interacting with other logs
* [ ] Draggable/collapsable workflow map (event nav)

#### Build initializing 
![setup](https://user-images.githubusercontent.com/78533/35757246-1f7a19a6-0823-11e8-885a-fe82bb27285e.png)
* [x] "Setting up Build" with spinner next to steps heading
* [x] Status icons are empty circles when step hasn't run

#### Step timed out (Stretch - Data not available)
![timeout](https://user-images.githubusercontent.com/78533/35757258-2ab52158-0823-11e8-8230-3eb9f25ffdd3.png)
* [ ] Indicator with step when build timed out

Stretch Goals (not mocked):
* [ ] Permalinks to steps
* [ ] Display metadata
* [ ] One-time load of all step logs when step already complete? May require api changes.

Edit:
* Marked step timeout UX as a stretch goal, as the data isn't yet available for the frontend to consume.

**Comment by renaud-yahoo** [comment]
Some comments and observations, as I spoke to @jithin1987 on this matter.

- The redesign is extremely clean and functional. I like this.
- As far as the "Build Top Bar" (not the absolute top bar in black) is concerned, it's a very interesting design, but I'd do *one* thing differently. From my point of view, the "white build top bar" contains functional information on the repository (screwdriver-cd/screwdriver, master, github source), and on the build job as well (main, commit, duration, user, used container [shorthand]). That being said, as far as build job information is concerned, while I do appreciate we list the user there, I don't think it's quite as important as the rest (main, commit, duration, container). So, my suggestion would be to move it to the repository column, but make it right-justified, so that we have a logic separation between repository and triggering user, as well as more space for important build information. Here's an altered mockup that shows the idea.
![build-screen-alted](https://user-images.githubusercontent.com/12864122/35818242-5c5d76a0-0a54-11e8-9318-b2526250e0dd.png)
- The page itself, with the steps, should not be the "Landing page". Some projects that would be "currently running" might have extremely verbose, long-haul steps that have so much logging that it could take megabytes of transfer to download the logs themselves, not to mention the page itself taking a while to load because of that. I would recommend finding a way to describe a build's "Current status" as a landing instead.
- The "Artifacts" section is in danger of being overloaded due to any given project being able to have multiple artifacts. There should be a way for projects to be able to define "Favorite Artifacts", either through a filter/regex or just through specific naming (regex/filters is most likely the better implementation), and then have the Artifacts section having a "More..." link that shows all of the artifacts
- The "Sections" in the steps is really interesting, but from the mocks, apparently limited to Setup and Teardown. Could the Templates be able to define sections as well? It would be really interesting to have step grouping as a feature.
- Can we have the "Yellow/Unstable" status as well here? I only see Green (success; maybe allow changing those colors as well, since some cultures use a different color, such as Blue) and Red (failure) in the mocks.

That's all for now. :)

**Comment by tkyi** [comment]
@renaud-yahoo I've never really understood the use case for the "Yellow/Unstable" status. Could you elaborate here?

**Comment by renaud-yahoo** [comment]
Sure.

Though it might be fundamentally "not completely right" to allow a build that doesn't pass *all* the tests to actually provide users with artifacts easily, I would argue that a "development build" can be considered a "successful build" if it can provide artifacts; BUT, in order to be considered "stable", it also has to provide test results making it clear that the build is stable.

Let's say, for example, that I'm working on a Game engine in C++.

- At first, it doesn't even compile, or compiles but doesn't link. That, obviously, results in a failure, because the compiler itself drops an exit code that's not 0, failing the whole step.
- When my engine would reach compilable step, the build obviously would become Green, as I do not have verification steps. Being a smart and diligent programmer, I would add unit tests to the process, that would be allowed to fail without failing the build itself. At this point, the build is `Unstable` (yellow), as no step would fundamentally fail, but some conditions would not be met for the build to be considered `Stable` (green/blue).
  - One advantage of having `Unstable` builds is that, in addition to the artifacts being readily available, it's made obvious that there is an issue with the build aside from it being successful. In the case of non-pipelined builds (a scenario that SD4 should support at some point), having an obvious UI clue that a given build has some issues unrelated to compilation is a good feature to have.
- Finally, when all passes properly (pipeline or not), then we get the all-green.

Of course, I would accept that there is an argument to be made about pipeline states and just doing a given test later in the pipeline. That being said, for non-web platforms, this would require docker container persistence, which I am not sure SD4 supports or provides at this point; sadly, pipelining the test phase becomes an unacceptable option for any build depending on compilation instead of simple text file assemblage.

**Comment by petey** [comment]
* User Link: I think it would introduce confusion to move the user where you suggested. The repo, branch, scm line shouldn't have anything to do with a single user, but the build does. Also, it could get a little strange having a user icon there right underneath the login/profile icon in the header.

* Logs: I agree that something needs to happen about the log view especially in the case where the user is spitting out MB of logs. I'm not really sure what is the best solution, though. Spitting out overly verbose logs to stdout is a user's self-imposed problem. Were we to truncate the logs, users would complain that they can not see everything. As you suggest, we could remove the feature that automatically displays the running or error logs, but there's not much to display in that space otherwise. We aren't parsing logs for errors. We could discuss this in another ticket.

* Artifacts: That's an interesting solution to another self-imposed user problem. Since screwdriver doesn't consume test results, coverage files, docs, or anything else that is thrown in the artifacts directory, it might be beneficial in the short term to bundle these files up to minimize the number of artifacts generated.

* Step Sections: That's a great idea. I actually want to do that. Can you file another ticket for that specifically?

* Unstable: Even given your explanation, I'm still not sure I see the value of adding an `UNSTABLE` state to builds/steps. There's nothing preventing a user from shipping an artifact to some repository regardless of the results of their tests, and promoting that artifact's use based on test results. The part that is missing is allowing you to inform people easily that additional action is needed (in some situations). This, however, is a discussion for another ticket.

**Comment by okuryu** [comment]
The improvement point I want to expect most is the easy to copy and paste build logs. Current build logs is hard to copy multi lines clean, it's a bad experience to me. I think many customers often paste a part of build logs in chat rooms and docs to communicate to co-workers. Not sure it's the scope of this issue. Any thoughts?

**Comment by renaud-yahoo** [comment]
Having a button to either "Copy to Clipboard" or "Download step log" would actually be an interesting feature.

**Comment by okuryu** [comment]
I just thought about "Copy to Clipboard". I've been using Screwdriver and Travis CI for many years, but I have not seen much of the scene I need to download the full build logs as a customer. Anyway, it's just my two cents.

**Comment by petey** [comment]
# 3/8
* The basic design of the page is complete, per the mocks. I've still got a bunch of log interaction stuff to work out, WRT scrolling behaviors and caching. 
* I added a button to abort or restart a build (not shown in the mocks). I may still need to add some logic to determine if the button should even be shown.
* I added buttons to "Go to top", "Go to bottom" of the logs (not shown in mocks). 
* Previously, logs were "cached" in the DOM, since there was a log panel for each step. This is no longer the case. I've added a caching behavior to the log component, but I'm worried about the memory usage of this component for large logs. Redraw time for logs is also substandard. May have to think of a different way to tackle this.
* I'm still trying to think of a way to implement the log view such that copying the logs isn't so terrible. Copy-to-clipboard is tricky, without form elements, but not impossible (can always do that off-screen). Downloading the log directly might require some api changes.

**Comment by petey** [comment]
# 3/14
Played around a lot more with the log component
* Removed the ability to select timestamps when copying, so copy/paste of logs works a lot better (but you lose the timestamps).
* Added a feature that allows you to see the timestamp of the log line, elapsed time since build started, and elapsed time since step started. Can change between them by clicking any timestamp.
* Logs once again automatically scroll to the bottom, unless the user is scrolling around themselves.

**Comment by petey** [comment]
# 3/19
* Fixed a bunch of broken tests
* Removed unused build page components
* Rebased with master changes for guest user support

**Comment by tkyi** [comment]
This change has been merged and verified.

**Comment by drewfish** [comment]
yeah the workflow map would be great. or if that's tricky even just a list of links to downstream build(s) (once they've started)
