### ISSUE TITLE
getting slower to show pipeline list

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#880]
Currently the pipeline list page doesn't have pagination capability. If I have thousands of pipelines in my cluster, it takes very long to load pipeline list and render them.
I tested with my cluster which has 2000 pipelines, it takes 1 second to load pipeline JSON from API and 5 seconds to render on a browser. It will be still getting slower if I add more pipelines.

It would be nice to have pagination or number limit on pipeline list page.

**Comment by tkyi** [comment]
Related to https://github.com/screwdriver-cd/screwdriver/issues/233

**Comment by tkyi** [comment]
This story would greatly speed up interaction with the pipeline search/list page. It should be pretty similar to the events list pagination story.

## Implementation

- [x] ~[models] Add `list` method with optional pagination for pipelineFactory~ handled by baseFactory `list` (https://github.com/screwdriver-cd/models/blob/master/lib/baseFactory.js#L126-L133)
- [x] ~[screwdriver] Pass pagination from GET `pipelines` endpoint to models `list` method~ already exists (https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/list.js#L40-L45)
- [ ] [UI] Update UI to handle pipeline list pagination

**Comment by tkyi** [comment]
**Update 9/17:**
The pagination is almost complete, but there’s an issue with sorting the pipelines alphabetically by name. Since we’ve added pagination, we can no longer do the sorting in the UI, it must be done when making the call to the datastore.

The issue is that the information needed, `name`, is stored in a JSON string in `scmRepo` in the DB:
```
{"branch":"tkyi-patch-1","name":"tkyi/mytest","url":"https://git.ouroath.com/tkyi/mytest/tree/tkyi-patch-1"}
```
Initially, we tried to use change the `sortKey` to `scmRepo.name`(https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L367-L372), but parsing the JSON string is difficult.

The alternative solution we're thinking about is adding `name` as its own field at the root level in the pipeline object, but this change will require a data migration.

**Comment by tkyi** [comment]
## Manual Steps for Existing Databases
In order to use these latest changes, you will need to do some SQL queries to migrate data from `scmRepo` to the new `name` field. This `name` field will be used for sorting and searching in the Search UI. 

### Without migrating
If no migration is done, pipelines will show up sorted by `id` in the Search page. Pipelines will not be returned in search results until a `sync` or `update` is done on them (either from the UI or by interacting with the pipeline in some way in the UI).

### Steps to migrate
1. Pull in the new API (**v0.5.466**). This is necessary for the `name` column to be created in the DB.
2. Take a snapshot or backup your DB.
3. Set pipeline `name`. This requires two calls in postgres: one to extract the pipeline name data, the second to remove the curly braces (`{` and `}`) injected by the regexp call.
```
UPDATE public.pipelines
SET name = regexp_matches("scmRepo", '.*name":"(.*)",.*')
```
```
UPDATE public.pipelines
SET name = btrim(name, '{}')
```
4. Pull in the new UI (**v1.0.331**).
5. _Optionally, you can post a banner at to let users know they might need to sync their pipelines if it is not showing up in search results. Make a call to `POST /banners` with proper auth and body like:_
```
{
  "message": "If your pipeline is not showing up in Search results, go to the pipeline Options tab and Sync the pipeline.",
  "isActive": true,
  "type": "info"
}
```

**Comment by tkyi** [comment]
This feature is finished. See instructions [above](https://github.com/screwdriver-cd/screwdriver/issues/880#issuecomment-422974436) to use this feature.
