### ISSUE TITLE
Proposal for Merging Code bases

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#902]
Currently, to contribute a new feature to the Screwdriver API, you most likely need to touch the following code bases:
 - [`screwdriver`](https://github.com/screwdriver-cd/screwdriver)
 - [`models`](https://github.com/screwdriver-cd/models)
 - [`data-schema`](https://github.com/screwdriver-cd/data-schema)

That means most changes we need to make are done in stages with phrases like "merge this first" and what not.  Each time those stages are merged, the entire code base is temporarily broken and we have to wait to either resolve everything or rollback.

These modules are primarily used by the core Screwdriver repository (the API), so why do we keep them separate?

The longer we've been working on this, the more I think these code bases should be merged into the main repository.  This will improve local development, feature merging, and onboarding of new developers.

I would also be willing to argue that more repositories should be included in that merge, like:
 - [`scm-router`](https://github.com/screwdriver-cd/scm-router)
 - [`workflow-parser`](https://github.com/screwdriver-cd/workflow-parser)
 - [`config-parser`](https://github.com/screwdriver-cd/config-parser)
 - [`command-validator`](https://github.com/screwdriver-cd/command-validator)
 - [`template-validator`](https://github.com/screwdriver-cd/template-validator)

And then it might be a stretch, but maybe include base libraries as well (all sub-classed repos will need to use peerDependency or something):
 - [`executor-base`](https://github.com/screwdriver-cd/executor-base)
 - [`datastore-base`](https://github.com/screwdriver-cd/datastore-base)
 - [`scm-base`](https://github.com/screwdriver-cd/scm-base)
 - [`notifications-base`](https://github.com/screwdriver-cd/notifications-base)
 - [`build-bookend`](https://github.com/screwdriver-cd/build-bookend)

Thoughts?

**Comment by d2lam** [comment]
I'm torn on this. In the beginning when we first started the project, we **specifically said** we wanted to split them up. The reason is the code base would be smaller and it will not be as hard to read thousands lines of code just to understand and fix 1 small line in `scm-github` for example. I'm leaning toward keeping them separate. I personally find it cleaner this way than reading a big repo with tons of things inside and takes forever to figure out what's going on.

`Each time those stages are merged, the entire code base is temporarily broken`
I'm not sure what you mean by this. If the change is not meant to be backward compatible, then it should have been a major version bump. And it will not affect anything until we agree to pull in the major change.

**Comment by petey** [comment]
Given the relative maturity of `model` and `data-schema` now, compared to when the project started, this seems reasonable. There doesn't appear to be much use-case to keep them separate, apart from the notion of having distinct responsibilities for each module, and the added benefits that adds to maintenance.

I would argue against bundling all those other things into the api as some represent some fairly complex algorithms that probably should live and be tested independently from the rest of the api.

**Comment by FenrirUnbound** [comment]
This is essentially a "should we convert this into a mono repo" proposition. For me, the standard arguments for either side come to mind, so I won't bring those up because it doesn't answer your question.

I would vote to keep them as they are today: separate. The practice of having the modules separate helped us better insulate inter-dependencies that we would have otherwise hardcoded.

Take for instance this -> https://github.com/screwdriver-cd/screwdriver/blob/master/bin/server#L31. (Yes, these configurations are incredibly limited, but it's not the point) If we never kept them separate, the way we would've handled "plugins" would be in a way worse state.

Looking forward, if we have plans on updating how Auth works, some of those modules would end up being separate anyways in order to be shared between each other.

> This will improve local development, feature merging, and onboarding of new developers.

Just keep in mind that this is 1 of _many_ different solutions that address these points.

I do agree that, beyond the API, some of the other modules could be merged together. But that's neither here nor there.

**Comment by stjohnjohnson** [comment]
Good discussions all around.  Sound like we have a mixed result.  Let's table this for discussion in Q2 or Q3.
