### ISSUE TITLE
Build artifacts cannot be saved after 2 hours from starting a build

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#998]
**What happened**:
- If a build takes more than 2 hours, the logs are not saved on store. 
- It is also a problem that a user cannot notice the situation.
  - It looks a build is stopped, but the build is proceeding actually.

The cause might be a expired token.
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/auth/index.js#L18
It might be reasonable that SDadmin can change this variable, but that is now fixed value.

**What you expected to happen**:
Token's expired period can be set by SDadmin, and store can save logs in the period.
or
Show messages that store does not save the build logs anymore.

**How to reproduce it**:
Start build that spends more than 2 hours.

**Comment by sakka2** [comment]
To resolve this Issue, I fixed Screwdriver API and models.

API: https://github.com/screwdriver-cd/screwdriver/pull/1062
models: https://github.com/screwdriver-cd/models/pull/245

## Objective
Expires time of JWT should be configurable based on the build timeout.
- Add `expiresSec` argument into [generateToken](https://github.com/screwdriver-cd/screwdriver/pull/1062/files#diff-cc45542b37e76ced3e366e4aa20f512cR91) method.
- `expiresSec` argument is defined in models, [lib/build.js#start()](https://github.com/screwdriver-cd/models/pull/245/files#diff-26b681bd4dac10f25d5293c7595c435bR154) method.
- `expiresSec` is configured based on build timeout value which is set by annotation or cluster config. If neither of them is set, default value (90minutes) will be set.
- Max value of `expiresSec` is 12 hours. Even if build timeout value which is set by annotation or cluster config is over 12 hours, JWT expires time value will be 12 hours.
- `expiresSec` will have buffer time (5minutes) more than build time out value, because sometimes it will take a time to start build since JWT is created.

**Comment by jithin1987** [comment]
Should be fixed with temporal JWT's
